import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'EN' | 'HI';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  EN: {
    // Hero Section
    'hero.badge': 'Trusted by 250+ retailers across India',
    'hero.title': 'Grow Your Retail Business with',
    'hero.titleHighlight': 'Digital Tools',
    'hero.description': 'Simple billing, smart customer management, and real-time insights — everything you need to compete with quick commerce and grow your store.',
    'hero.download': 'Download',
    'hero.watchDemo': 'Book a Demo',
    'hero.rating': '4.8/5 from 250+ reviews',
    
    // Stats
    'stats.retailers': 'Retailers Trust Us',
    'stats.transactions': 'Transactions Processed',
    'stats.revenue': 'Average Revenue Increase',
    'stats.rating': 'Customer Rating',
    
    // Challenge Section
    'challenge.title': 'Why Local Retailers Are Losing Customers',
    'challenge.subtitle': 'While apps deliver in 10 minutes, local stores still:',
    'challenge.point1': 'Losing customers to quick commerce apps',
    'challenge.point2': 'Manual billing wastes time & causes errors',
    'challenge.point3': 'No way to track or engage customers',
    'challenge.point4': 'No visibility into business performance',
    'challenge.solution': 'Lume Gives You the Digital Edge',
    'challenge.solutionDesc': 'Now not just billing, but a complete system to grow customers and sales — without expensive machines or technical hassle.',
    
    // Benefits
    'benefit.fastBilling.title': 'Fast & Easy Billing',
    'benefit.fastBilling.desc': 'Make bills in seconds—tax or non-tax, with image billing and simple templates. Less waiting, smoother checkout, happier customers.',
    'benefit.posIntegration.title': 'Works with Your Current POS',
    'benefit.posIntegration.desc': 'Use Lume with your existing POS system. No need to change machines—Lume reads all your bills in one place.',
    'benefit.engagement.title': 'Every Bill Helps You Get More Sales',
    'benefit.engagement.desc': 'Each bill can send offers, loyalty points, feedback links, and Google rating requests automatically. Customers remember your store and come back again.',
    'benefit.customerCapture.title': 'Customer Details Get Saved Automatically',
    'benefit.customerCapture.desc': 'Every bill saves who bought, what they bought, and when they bought it. Over time, you understand your customers better without extra work.',
    'benefit.smartOffers.title': 'Smart Offers That Increase Bill Value',
    'benefit.smartOffers.desc': 'Give the right offer at the right time—like tea with milk or related items with clothes. This helps customers buy more in the same visit.',
    'benefit.dashboard.title': 'See Your Business in One Screen',
    'benefit.dashboard.desc': 'Check sales, stock, customers, and offers from one simple dashboard. You always know how your shop is doing.',
    
    // How It Works
    'howItWorks.title': 'Start Selling Smarter in 4 Simple Steps',
    'howItWorks.subtitle': 'Get started in minutes and transform your retail business',
    'howItWorks.step1.title': 'Download the App',
    'howItWorks.step1.desc': 'Free download from Play Store. Setup takes just 5 minutes.',
    'howItWorks.step2.title': 'Add Your Products',
    'howItWorks.step2.desc': 'Scan barcodes or add manually. Bulk import available.',
    'howItWorks.step3.title': 'Start Billing',
    'howItWorks.step3.desc': 'Create digital bills and capture customer data automatically.',
    'howItWorks.step4.title': 'Grow Your Business',
    'howItWorks.step4.desc': 'Use insights and engagement tools to increase repeat customers.',
    'howItWorks.cta': 'Book a Demo',
    
    // Industries
    'industries.title': 'Built for All Types of Retail Stores',
    'industries.subtitle': 'Trusted by thousands of retailers across different industries. Lume works seamlessly for every type of store.',
    'industries.grocery': 'Grocery & Kirana Stores',
    'industries.fashion': 'Fashion & Apparel Stores',
    'industries.electronics': 'Electronics & Mobile Stores',
    'industries.pharmacy': 'Pharmacy & Medical Stores',
    'industries.general': 'General Stores',
    'industries.footwear': 'Footwear Stores',
    'industries.cosmetic': 'Cosmetic & Beauty Stores',
    'industries.stationery': 'Stationery & Book Stores',
    'industries.hardware': 'Hardware & Electrical Stores',
    'industries.bakery': 'Bakery & Sweet Shops',
    
    // Testimonials
    'testimonials.quote': 'Retailers Love Lume',
    'testimonials.subtitle': 'Join thousands of store owners who have transformed their business with Lume.',
    
    // Final CTA
    'cta.title': 'Ready to Grow Your Retail Business?',
    'cta.description': 'Join 250+ retailers who trust Lume. Book a demo today to see how it works.',
    'cta.startTrial': 'Book a Demo',
    'cta.contactSales': 'Contact Sales',
    
    // Products Page
    'products.hero.titleLine1': 'Billing that understands',
    'products.hero.titleLine2': 'your business',
    'products.hero.subtitle': 'Lume connects billing, customer data, campaigns, and analytics into a single retail intelligence platform.',
    'products.hero.bookDemo': 'Book a Demo',
    'products.hero.seeFeatures': 'See Features',
    'products.whatIsLume.title': 'What is Lume?',
    'products.whatIsLume.point1': 'Lume is a complete retail platform that helps you move beyond basic billing.',
    'products.whatIsLume.point2': 'It works with your existing POS or web billing system, reads every bill automatically, and converts billing data into customer insights, loyalty, and growth tools.',
    'products.coreCapabilities.title': 'What You Can Do With Lume',
    'products.coreCapabilities.billing.title': 'Billing & POS Integration',
    'products.coreCapabilities.billing.desc': 'Seamless billing with flexible integration options',
    'products.coreCapabilities.billing.feature1': 'Tax & non-tax billing',
    'products.coreCapabilities.billing.feature2': 'Quick billing & image billing',
    'products.coreCapabilities.billing.feature3': 'Multiple billing templates',
    'products.coreCapabilities.billing.feature4': 'POS plugin (connect any existing POS)',
    'products.coreCapabilities.digitalBills.title': 'Smart Digital Bills',
    'products.coreCapabilities.digitalBills.desc': 'Transform bills into customer engagement tools',
    'products.coreCapabilities.digitalBills.feature1': 'WhatsApp / SMS / Email bills',
    'products.coreCapabilities.digitalBills.feature2': 'Promotions inside bills',
    'products.coreCapabilities.digitalBills.feature3': 'Feedback & Google rating',
    'products.coreCapabilities.digitalBills.feature4': 'Social sharing & refer & earn',
    'products.coreCapabilities.loyalty.title': 'Customer & Loyalty Engine',
    'products.coreCapabilities.loyalty.desc': 'Build stronger relationships with every purchase',
    'products.coreCapabilities.loyalty.feature1': 'Auto customer capture',
    'products.coreCapabilities.loyalty.feature2': 'Complete purchase history',
    'products.coreCapabilities.loyalty.feature3': 'Loyalty points & coupons',
    'products.coreCapabilities.loyalty.feature4': 'Repeat customer tracking',
    'products.coreCapabilities.analytics.title': 'Analytics & Reports',
    'products.coreCapabilities.analytics.desc': 'Make decisions based on data, not guesswork',
    'products.coreCapabilities.analytics.feature1': 'Sales & product analytics',
    'products.coreCapabilities.analytics.feature2': 'Customer behavior insights',
    'products.coreCapabilities.analytics.feature3': 'Time-based insights',
    'products.coreCapabilities.analytics.feature4': 'Downloadable reports',
    'products.coreCapabilities.campaign.title': 'Campaign Manager',
    'products.coreCapabilities.campaign.desc': 'Reach the right customers at the right time',
    'products.coreCapabilities.campaign.feature1': 'Segmented campaigns',
    'products.coreCapabilities.campaign.feature2': 'Multiple channels',
    'products.coreCapabilities.campaign.feature3': 'Campaign performance tracking',
    'products.coreCapabilities.campaign.feature4': 'Automated workflows',
    'products.howItWorks.title': 'How Lume Fits Into Your Business',
    'products.howItWorks.step1.title': 'Bill from POS / Web / Plugin',
    'products.howItWorks.step1.desc': 'Use your existing system or Lume\'s web POS. Bill as usual.',
    'products.howItWorks.step2.title': 'Lume reads and unifies all bill data',
    'products.howItWorks.step2.desc': 'Every transaction is automatically captured and processed.',
    'products.howItWorks.step3.title': 'Smart bill goes to customer',
    'products.howItWorks.step3.desc': 'Digital bills with promotions, feedback links, and more.',
    'products.howItWorks.step4.title': 'Data powers analytics, loyalty & campaigns',
    'products.howItWorks.step4.desc': 'Insights drive better decisions and customer engagement.',
    'products.whoIsLumeFor.title': 'Built to Scale With You',
    'products.whoIsLumeFor.singleStore.title': 'Single store retailers',
    'products.whoIsLumeFor.singleStore.desc': 'Perfect for individual stores looking to digitize operations',
    'products.whoIsLumeFor.multiStore.title': 'Multi-store businesses',
    'products.whoIsLumeFor.multiStore.desc': 'Manage multiple locations with unified data and insights',
    'products.whoIsLumeFor.growingChains.title': 'Growing retail chains',
    'products.whoIsLumeFor.growingChains.desc': 'Scale your operations with enterprise-grade tools',
    'products.lumeShop.title': 'Extend Lume With Lume Shop',
    'products.lumeShop.desc': 'Lume Shop lets you turn your retail store into a hyperlocal online store. Orders, customers, and data stay connected with Lume.',
    'products.lumeShop.comingSoon': 'Coming Soon',
    'products.lumeShop.preview': 'Lume Shop Preview',
    'products.trust.retailers': 'Retailers',
    'products.trust.transactions': 'Transactions',
    'products.trust.rating': 'Rating',
    'products.trust.growth': 'Average Sales Growth',
    'products.trust.testimonial': 'Lume changed how we manage our store. Everything is connected now.',
    'products.trust.testimonialAuthor': 'Retail Store Owner',
    'products.cta.title': 'Ready to See Lume in Action?',
    'products.cta.bookDemo': 'Book a Demo',
    'products.cta.viewPricing': 'View Pricing',
    
    // Header Navigation
    'nav.forRetailers': 'For Retailers',
    'nav.solutions': 'Solutions',
    'nav.products': 'Products',
    'nav.resources': 'Resources',
    'nav.pricing': 'Pricing',
    
    // Footer
    'footer.tagline': 'We turn billing into a growth engine for retailers.',
    'footer.company': 'Company',
    'footer.products': 'Products',
    'footer.solutions': 'Solutions',
    'footer.resources': 'Resources',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.investors': 'Investors',
    'footer.contact': 'Contact',
    'footer.webPos': 'Web POS – Online Billing',
    'footer.posPlugin': 'POS Plugin – Add‑on for Billing',
    'footer.analytics': 'Analytics Dashboard',
    'footer.campaign': 'Campaign Manager',
    'footer.lume': 'Lume',
    'footer.lumeShopComingSoon': 'Lume Shop (Coming Soon)',
    'footer.smartBilling': 'Smart Billing',
    'footer.customerAnalytics': 'Customer Analytics',
    'footer.loyalty': 'Loyalty & Coupons',
    'footer.campaignManagement': 'Campaign Management',
    'footer.caseStudies': 'Case Studies',
    'footer.blog': 'Blog',
    'footer.guides': 'Guides',
    'footer.helpCenter': 'Help Center',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.copyright': 'All rights reserved.',
    
    // Book Demo Page
    'demo.title': 'Book a Demo',
    'demo.subtitle': 'See how ल्यूम can transform your retail business. Schedule a personalized demo with our team.',
    'demo.formTitle': 'Schedule Your Demo',
    'demo.name': 'Full Name',
    'demo.namePlaceholder': 'Enter your full name',
    'demo.phone': 'Phone Number',
    'demo.phonePlaceholder': 'Enter your phone number',
    'demo.email': 'Email Address',
    'demo.emailPlaceholder': 'Enter your email address',
    'demo.selectDate': 'Select Date',
    'demo.selectTime': 'Select Time Slot',
    'demo.submit': 'Book Demo',
    'demo.successTitle': 'Demo Booked Successfully!',
    'demo.successMessage': 'We\'ll send you a confirmation email with the meeting details shortly.',
    'demo.whatToExpect': 'What to Expect',
    'demo.expect1': 'Live walkthrough of all features',
    'demo.expect2': 'See how it works for your store type',
    'demo.expect3': 'Get answers to all your questions',
    'demo.expect4': 'Learn about pricing and setup',
    'demo.officeHours': 'Office Hours',
    'demo.weekdays': 'Monday - Friday',
    'demo.weekend': 'Saturday & Sunday',
    'demo.closed': 'Closed',
    'demo.today': 'Today',
    'demo.tomorrow': 'Tomorrow',
    'demo.dayAfter': 'Day After',
    
    // For Retailers Page
    'forRetailers.hero.badge': 'Rated 4.8/5 by 250+ retailers',
    'forRetailers.hero.title': 'Turn Your Store into a',
    'forRetailers.hero.titleHighlight': 'Modern Business',
    'forRetailers.hero.description': 'Lume gives you everything you need to compete with quick commerce — digital billing, customer insights, and smart tools that work on any phone.',
    'forRetailers.hero.bookDemo': 'Book a Demo',
    'forRetailers.hero.viewPricing': 'View Pricing',
    
    'forRetailers.problems.title': 'Your Problems, Solved',
    'forRetailers.problems.subtitle': 'We built Lume for the real challenges Indian retailers face every day.',
    'forRetailers.problems.problem1': 'Manual billing wastes hours daily',
    'forRetailers.problems.solution1': 'Digital bills in under 10 seconds',
    'forRetailers.problems.problem2': 'No customer data or repeat buyers',
    'forRetailers.problems.solution2': 'Auto-capture customer info & history',
    'forRetailers.problems.problem3': 'Credit (udhaar) leads to losses',
    'forRetailers.problems.solution3': 'Smart tracking & auto-reminders',
    'forRetailers.problems.problem4': 'Can\'t track real profit margins',
    'forRetailers.problems.solution4': 'Real-time analytics dashboard',
    'forRetailers.problems.problem5': 'Customers forget your store',
    'forRetailers.problems.solution5': 'Automated WhatsApp offers',
    
    'forRetailers.howItWorks.title': 'Go Digital in 3 Easy Steps',
    'forRetailers.howItWorks.step1.title': 'Download & Setup',
    'forRetailers.howItWorks.step1.description': 'Download from Play Store. Add your store details and products in minutes.',
    'forRetailers.howItWorks.step1.time': '5 minutes',
    'forRetailers.howItWorks.step2.title': 'Start Billing',
    'forRetailers.howItWorks.step2.description': 'Create professional GST bills instantly. Customer data captured automatically.',
    'forRetailers.howItWorks.step2.time': '10 seconds/bill',
    'forRetailers.howItWorks.step3.title': 'Grow Revenue',
    'forRetailers.howItWorks.step3.description': 'Use insights & engagement tools to bring customers back and increase sales.',
    'forRetailers.howItWorks.step3.time': '25% avg. growth',
    
    'forRetailers.industries.title': 'Built for Your Type of Store',
    'forRetailers.industries.subtitle': 'Whether you sell groceries, fashion, or electronics — Lume adapts to your business.',
    'forRetailers.industries.grocery.name': 'Grocery & Kirana',
    'forRetailers.industries.grocery.description': 'Inventory tracking, expiry alerts, supplier management',
    'forRetailers.industries.fashion.name': 'Fashion & Apparel',
    'forRetailers.industries.fashion.description': 'Size/color variants, seasonal sales, loyalty programs',
    'forRetailers.industries.electronics.name': 'Electronics',
    'forRetailers.industries.electronics.description': 'Warranty tracking, service reminders, high-value billing',
    'forRetailers.industries.general.name': 'General Stores',
    'forRetailers.industries.general.description': 'Multi-category management, flexible pricing, credit tracking',
    
    'forRetailers.testimonials.title': 'Real Results from Real Retailers',
    'forRetailers.testimonials.story1.metric': '40%',
    'forRetailers.testimonials.story1.outcome': 'increase in repeat customers',
    'forRetailers.testimonials.story1.quote': 'My customers now get WhatsApp bills. They love it and keep coming back.',
    'forRetailers.testimonials.story1.name': 'Vijay Grocery',
    'forRetailers.testimonials.story2.metric': '₹50K',
    'forRetailers.testimonials.story2.outcome': 'saved in bad debts monthly',
    'forRetailers.testimonials.story2.quote': 'The credit tracking feature has transformed how I manage udhaar.',
    'forRetailers.testimonials.story2.name': 'Style Corner',
    'forRetailers.testimonials.story3.metric': '2 hours',
    'forRetailers.testimonials.story3.outcome': 'saved daily on billing',
    'forRetailers.testimonials.story3.quote': 'What took hours now takes minutes. I can focus on customers.',
    'forRetailers.testimonials.story3.name': 'City Mart',
    
    'forRetailers.roi.title': 'Lume Pays for Itself in the First Month',
    'forRetailers.roi.description': 'Our retailers see measurable ROI within weeks of starting. Here\'s what you can expect:',
    'forRetailers.roi.timeSaved.value': '2 hours/day',
    'forRetailers.roi.timeSaved.label': 'Time saved on billing',
    'forRetailers.roi.creditRecovered.value': '₹15,000/month',
    'forRetailers.roi.creditRecovered.label': 'Credit recovered',
    'forRetailers.roi.repeatCustomers.value': '30% वृद्धि',
    'forRetailers.roi.repeatCustomers.label': 'More repeat customers',
    'forRetailers.roi.averageROI.value': '10x return on investment',
    'forRetailers.roi.averageROI.label': 'Average ROI',
    
    'forRetailers.testimonials.story1.location': 'Ahmedabad',
    'forRetailers.testimonials.story2.location': 'Mumbai',
    'forRetailers.testimonials.story3.location': 'Thane',
    
    'forRetailers.cta.title': 'Ready to Get Started?',
    'forRetailers.cta.feature1': 'Live demo with all features',
    'forRetailers.cta.feature2': 'No credit card required',
    'forRetailers.cta.feature3': 'Free onboarding support',
    'forRetailers.cta.feature4': 'Works on any Android phone',
    'forRetailers.cta.feature5': 'Cancel anytime, no questions asked',
    'forRetailers.cta.bookDemo': 'Book a Demo',
    'forRetailers.cta.viewPricing': 'Or view pricing plans',
  },
  HI: {
    // Hero Section
    'hero.badge': 'भारत के 250+ दुकानदारों का भरोसा',
    'hero.title': 'अपने दुकान के बिज़नेस को',
    'hero.titleHighlight': 'डिजिटल टूल्स से बढ़ाइए',
    'hero.description': 'बिलिंग से लेकर ग्राहकों की जानकारी और बिक्री की पूरी रिपोर्ट — सब कुछ एक ही मोबाइल ऐप में। अब बड़ी डिलीवरी ऐप्स से मुकाबला करना आसान।',
    'hero.download': 'डाउनलोड करें',
    'hero.watchDemo': 'डेमो बुक करें',
    'hero.rating': '4.8/5 रेटिंग (250+ दुकानदारों की राय)',
    
    // Stats
    'stats.retailers': 'दुकानदार जुड़े हुए',
    'stats.transactions': 'का लेन-देन',
    'stats.revenue': 'बिज़नेस ग्रोथ',
    'stats.rating': 'कस्टमर रेटिंग',
    
    // Challenge Section
    'challenge.title': 'लोकल दुकानदार ग्राहक क्यों खो रहे हैं?',
    'challenge.subtitle': 'आज जहाँ ऐप्स 10 मिनट में डिलीवरी दे रही हैं, वहीं लोकल दुकानों में अब भी:',
    'challenge.point1': 'क्विक कॉमर्स ऐप्स से ग्राहक खो रहे हैं',
    'challenge.point2': 'हाथ से बिल बनाना समय बर्बाद करता है और गलतियाँ होती हैं',
    'challenge.point3': 'ग्राहकों को ट्रैक या जुड़ने का तरीका नहीं',
    'challenge.point4': 'दुकान का सही हिसाब समझ नहीं आता',
    'challenge.solution': 'ल्यूम देता है आपकी दुकान को डिजिटल ताकत',
    'challenge.solutionDesc': 'अब सिर्फ बिलिंग नहीं, बल्कि ग्राहक बढ़ाने और बिक्री बढ़ाने का पूरा सिस्टम — वो भी बिना महंगे मशीन या टेक्निकल झंझट के।',
    
    // Benefits
    'benefit.fastBilling.title': 'तेज़ और आसान बिलिंग',
    'benefit.fastBilling.desc': 'सेकंड्स में बिल बनाइए — टैक्स हो या बिना टैक्स। ग्राहक कम इंतज़ार करेंगे, लाइन छोटी होगी।',
    'benefit.posIntegration.title': 'आपके मौजूदा POS के साथ काम करता है',
    'benefit.posIntegration.desc': 'नई मशीन लेने की जरूरत नहीं। ल्यूम आपके पुराने सिस्टम के साथ भी चलता है।',
    'benefit.engagement.title': 'हर बिल से दोबारा बिक्री',
    'benefit.engagement.desc': 'हर बिल के साथ ऑफर, पॉइंट्स, फीडबैक और Google रेटिंग अपने आप चली जाती है। ग्राहक आपको याद रखता है।',
    'benefit.customerCapture.title': 'ग्राहक की जानकारी अपने आप सेव',
    'benefit.customerCapture.desc': 'किसने क्या खरीदा, कब खरीदा — सब रिकॉर्ड हो जाता है, बिना अलग मेहनत के।',
    'benefit.smartOffers.title': 'स्मार्ट ऑफर जो बिल बढ़ाए',
    'benefit.smartOffers.desc': 'सही समय पर सही ऑफर — जैसे चाय के साथ बिस्किट, कपड़ों के साथ मैचिंग आइटम।',
    'benefit.dashboard.title': 'पूरी दुकान एक स्क्रीन पर',
    'benefit.dashboard.desc': 'बिक्री, स्टॉक, ग्राहक और ऑफर — सब एक ही डैशबोर्ड में।',
    
    // How It Works
    'howItWorks.title': '4 आसान स्टेप में शुरुआत',
    'howItWorks.subtitle': 'मिनटों में शुरू करें और अपने दुकान के बिज़नेस को बदलें',
    'howItWorks.step1.title': 'ऐप डाउनलोड करें',
    'howItWorks.step1.desc': 'Play Store से — 5 मिनट में सेटअप',
    'howItWorks.step2.title': 'प्रोडक्ट जोड़ें',
    'howItWorks.step2.desc': 'बारकोड स्कैन या मैन्युअली',
    'howItWorks.step3.title': 'बिलिंग शुरू करें',
    'howItWorks.step3.desc': 'डिजिटल बिल और ग्राहक डेटा अपने आप',
    'howItWorks.step4.title': 'बिज़नेस बढ़ाइए',
    'howItWorks.step4.desc': 'रिपोर्ट और ऑफर के साथ',
    'howItWorks.cta': 'डेमो बुक करें',
    
    // Industries
    'industries.title': 'सभी तरह की दुकानों के लिए बनाया गया',
    'industries.subtitle': 'हजारों दुकानदारों का भरोसा। ल्यूम हर तरह की दुकान के लिए काम करता है।',
    'industries.grocery': 'किराना एवं जनरल स्टोर',
    'industries.fashion': 'कपड़े एवं रेडीमेड स्टोर',
    'industries.electronics': 'इलेक्ट्रॉनिक्स एवं मोबाइल स्टोर',
    'industries.pharmacy': 'फार्मेसी एवं मेडिकल स्टोर',
    'industries.general': 'जनरल स्टोर',
    'industries.footwear': 'जूते एवं फुटवियर स्टोर',
    'industries.cosmetic': 'कॉस्मेटिक एवं ब्यूटी स्टोर',
    'industries.stationery': 'स्टेशनरी एवं बुक स्टोर',
    'industries.hardware': 'हार्डवेयर एवं इलेक्ट्रिकल स्टोर',
    'industries.bakery': 'बेकरी एवं मिठाई की दुकान',
    
    // Testimonials
    'testimonials.quote': 'दुकानदार ल्यूम से प्यार करते हैं',
    'testimonials.subtitle': 'हजारों दुकान मालिकों के साथ जुड़ें जिन्होंने ल्यूम के साथ अपने बिज़नेस को बदल दिया है।',
    
    // Final CTA
    'cta.title': 'अपने दुकान के बिज़नेस को बढ़ाने के लिए तैयार हैं?',
    'cta.description': '250+ दुकानदारों के साथ जुड़ें जो ल्यूम पर भरोसा करते हैं। आज ही डेमो बुक करें और देखें कि यह कैसे काम करता है।',
    'cta.startTrial': 'डेमो बुक करें',
    'cta.contactSales': 'सेल्स से संपर्क करें',
    
    // Book Demo Page
    'demo.title': 'डेमो बुक करें',
    'demo.subtitle': 'देखें कि ल्यूम आपके दुकान के बिज़नेस को कैसे बदल सकता है। हमारी टीम के साथ एक व्यक्तिगत डेमो शेड्यूल करें।',
    'demo.formTitle': 'अपना डेमो शेड्यूल करें',
    'demo.name': 'पूरा नाम',
    'demo.namePlaceholder': 'अपना पूरा नाम दर्ज करें',
    'demo.phone': 'फोन नंबर',
    'demo.phonePlaceholder': 'अपना फोन नंबर दर्ज करें',
    'demo.email': 'ईमेल पता',
    'demo.emailPlaceholder': 'अपना ईमेल पता दर्ज करें',
    'demo.selectDate': 'तारीख चुनें',
    'demo.selectTime': 'समय स्लॉट चुनें',
    'demo.submit': 'डेमो बुक करें',
    'demo.successTitle': 'डेमो सफलतापूर्वक बुक हो गया!',
    'demo.successMessage': 'हम आपको जल्द ही मीटिंग विवरण के साथ एक पुष्टिकरण ईमेल भेजेंगे।',
    'demo.whatToExpect': 'क्या उम्मीद करें',
    'demo.expect1': 'सभी सुविधाओं का लाइव वॉकथ्रू',
    'demo.expect2': 'देखें कि यह आपके दुकान के प्रकार के लिए कैसे काम करता है',
    'demo.expect3': 'अपने सभी सवालों के जवाब पाएं',
    'demo.expect4': 'कीमत और सेटअप के बारे में जानें',
    'demo.officeHours': 'कार्यालय समय',
    'demo.weekdays': 'सोमवार - शुक्रवार',
    'demo.weekend': 'शनिवार और रविवार',
    'demo.closed': 'बंद',
    'demo.today': 'आज',
    'demo.tomorrow': 'कल',
    'demo.dayAfter': 'परसों',
    
    // For Retailers Page
    'forRetailers.hero.badge': '250+ दुकानदारों का भरोसा | 4.8/5 रेटिंग',
    'forRetailers.hero.title': 'अपनी दुकान को बनाइए',
    'forRetailers.hero.titleMiddle': 'एक',
    'forRetailers.hero.titleHighlight': 'आधुनिक बिज़नेस',
    'forRetailers.hero.description': 'Lume आपको वो सभी स्मार्ट टूल देता है जिनसे आप क्विक कॉमर्स से टक्कर दे सकें — डिजिटल बिलिंग, ग्राहक की जानकारी और आसान सिस्टम जो किसी भी मोबाइल पर चलता है।',
    'forRetailers.hero.bookDemo': 'डेमो बुक करें',
    'forRetailers.hero.viewPricing': 'प्लान और कीमत देखें',
    
    'forRetailers.problems.title': 'आपकी रोज़ की परेशानियाँ — अब हल के साथ',
    'forRetailers.problems.subtitle': 'Lume खास तौर पर भारतीय दुकानदारों की असली समस्याओं को ध्यान में रखकर बनाया गया है।',
    'forRetailers.problems.problem1': 'हाथ से बिल बनाने में रोज़ घंटों बर्बाद होते हैं',
    'forRetailers.problems.solution1': '10 सेकंड में डिजिटल बिल तैयार',
    'forRetailers.problems.problem2': 'ग्राहकों की कोई जानकारी नहीं, दोबारा ग्राहक नहीं आते',
    'forRetailers.problems.solution2': 'ग्राहक की पूरी जानकारी अपने आप सेव होती है',
    'forRetailers.problems.problem3': 'उधार सही से न संभाल पाने से नुकसान होता है',
    'forRetailers.problems.solution3': 'उधार की स्मार्ट ट्रैकिंग और ऑटो रिमाइंडर',
    'forRetailers.problems.problem4': 'असली मुनाफ़ा समझ में नहीं आता',
    'forRetailers.problems.solution4': 'रीयल-टाइम बिज़नेस रिपोर्ट और डैशबोर्ड',
    'forRetailers.problems.problem5': 'ग्राहक आपकी दुकान को भूल जाते हैं',
    'forRetailers.problems.solution5': 'व्हाट्सऐप पर ऑटो ऑफ़र और मैसेज',
    
    'forRetailers.howItWorks.title': '3 आसान स्टेप में डिजिटल बनिए',
    'forRetailers.howItWorks.step1.title': 'डाउनलोड करें और सेटअप करें',
    'forRetailers.howItWorks.step1.description': 'Play Store से ऐप डाउनलोड करें और कुछ ही मिनटों में अपनी दुकान की जानकारी जोड़ें।',
    'forRetailers.howItWorks.step1.time': 'सिर्फ 5 मिनट',
    'forRetailers.howItWorks.step2.title': 'बिल बनाना शुरू करें',
    'forRetailers.howItWorks.step2.description': 'GST के साथ प्रोफेशनल बिल बनाएं। ग्राहक की जानकारी अपने आप सेव होगी।',
    'forRetailers.howItWorks.step2.time': 'हर बिल 10 सेकंड में',
    'forRetailers.howItWorks.step3.title': 'बिक्री बढ़ाइए',
    'forRetailers.howItWorks.step3.description': 'रिपोर्ट और कस्टमर टूल्स का इस्तेमाल करके ग्राहकों को दोबारा लाएं।',
    'forRetailers.howItWorks.step3.time': 'औसतन 25% बढ़ोतरी',
    
    'forRetailers.industries.title': 'हर तरह की दुकान के लिए बनाया गया',
    'forRetailers.industries.subtitle': 'Whether you sell groceries, fashion, or electronics — Lume adapts to your business.',
    'forRetailers.industries.grocery.name': 'किराना और ग्रोसरी स्टोर',
    'forRetailers.industries.grocery.description': 'स्टॉक ट्रैकिंग, एक्सपायरी अलर्ट, सप्लायर मैनेजमेंट',
    'forRetailers.industries.fashion.name': 'फैशन और कपड़ों की दुकान',
    'forRetailers.industries.fashion.description': 'साइज़ और कलर मैनेजमेंट, सीज़नल सेल, लॉयल्टी सिस्टम',
    'forRetailers.industries.electronics.name': 'इलेक्ट्रॉनिक्स स्टोर',
    'forRetailers.industries.electronics.description': 'वारंटी ट्रैकिंग, सर्विस रिमाइंडर, बड़े बिल आसान',
    'forRetailers.industries.general.name': 'जनरल स्टोर',
    'forRetailers.industries.general.description': 'मल्टी कैटेगरी स्टॉक, फास्ट बिलिंग, उधार मैनेजमेंट',
    
    'forRetailers.testimonials.title': 'असली दुकानदारों के असली नतीजे',
    'forRetailers.testimonials.story1.metric': '40%',
    'forRetailers.testimonials.story1.outcome': 'ज़्यादा दोबारा आने वाले ग्राहक',
    'forRetailers.testimonials.story1.quote': 'My customers now get WhatsApp bills. They love it and keep coming back.',
    'forRetailers.testimonials.story1.name': 'Vijay Grocery',
    'forRetailers.testimonials.story2.metric': '₹50K',
    'forRetailers.testimonials.story2.outcome': 'हर महीने ₹50,000 तक उधार की बचत',
    'forRetailers.testimonials.story2.quote': 'The credit tracking feature has transformed how I manage udhaar.',
    'forRetailers.testimonials.story2.name': 'Style Corner',
    'forRetailers.testimonials.story3.metric': '2 घंटे',
    'forRetailers.testimonials.story3.outcome': 'रोज़ 2 घंटे की बचत',
    'forRetailers.testimonials.story3.quote': 'What took hours now takes minutes. I can focus on customers.',
    'forRetailers.testimonials.story3.name': 'City Mart',
    
    'forRetailers.roi.title': 'पहले ही महीने में Lume अपनी कीमत निकाल देता है',
    'forRetailers.roi.description': 'हमारे दुकानदार शुरुआत के कुछ हफ्तों में ही नतीजे देखने लगते हैं। यहाँ वो है जो आप उम्मीद कर सकते हैं:',
    'forRetailers.roi.timeSaved.value': '2 घंटे/दिन',
    'forRetailers.roi.timeSaved.label': 'बिलिंग में रोज़ समय की बचत',
    'forRetailers.roi.creditRecovered.value': '₹15,000/महीना',
    'forRetailers.roi.creditRecovered.label': 'उधार की रकम वापस',
    'forRetailers.roi.repeatCustomers.value': '30% वृद्धि',
    'forRetailers.roi.repeatCustomers.label': 'ज़्यादा लौटने वाले ग्राहक',
    'forRetailers.roi.averageROI.value': '10 गुना निवेश पर रिटर्न',
    'forRetailers.roi.averageROI.label': 'औसतन 10 गुना रिटर्न',
    
    'forRetailers.testimonials.story1.location': 'अहमदाबाद',
    'forRetailers.testimonials.story2.location': 'मुंबई',
    'forRetailers.testimonials.story3.location': 'ठाणे',
    
    'forRetailers.cta.title': 'शुरू करने के लिए तैयार हैं?',
    'forRetailers.cta.feature1': 'सभी फीचर्स के साथ लाइव डेमो',
    'forRetailers.cta.feature2': 'कोई कार्ड की ज़रूरत नहीं',
    'forRetailers.cta.feature3': 'फ्री सेटअप और सपोर्ट',
    'forRetailers.cta.feature4': 'हर एंड्रॉयड मोबाइल पर काम करता है',
    'forRetailers.cta.feature5': 'जब चाहें बंद करें',
    'forRetailers.cta.bookDemo': 'डेमो बुक करें',
    'forRetailers.cta.viewPricing': 'या प्लान देखें',
    
    // Footer
    'footer.tagline': 'हम बिलिंग को दुकानदारों के लिए ग्रोथ इंजन में बदलते हैं।',
    'footer.company': 'कंपनी',
    'footer.products': 'उत्पाद',
    'footer.solutions': 'समाधान',
    'footer.resources': 'संसाधन',
    'footer.about': 'हमारे बारे में',
    'footer.careers': 'करियर',
    'footer.investors': 'निवेशक',
    'footer.contact': 'संपर्क करें',
    'footer.webPos': 'ऑनलाइन बिलिंग सिस्टम',
    'footer.posPlugin': 'बिलिंग सिस्टम का अतिरिक्त फीचर',
    'footer.analytics': 'एनालिटिक्स डैशबोर्ड',
    'footer.campaign': 'कैंपेन मैनेजर',
    'footer.lume': 'ल्यूम',
    'footer.lumeShopComingSoon': 'ल्यूम शॉप (जल्द आ रहा है)',
    'footer.smartBilling': 'स्मार्ट बिलिंग',
    'footer.customerAnalytics': 'ग्राहक एनालिटिक्स',
    'footer.loyalty': 'लॉयल्टी और कूपन',
    'footer.campaignManagement': 'कैंपेन प्रबंधन',
    'footer.caseStudies': 'केस स्टडीज',
    'footer.blog': 'ब्लॉग',
    'footer.guides': 'गाइड',
    'footer.helpCenter': 'हेल्प सेंटर',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'नियम और शर्तें',
    'footer.copyright': 'सभी अधिकार सुरक्षित।',
    
    // Header Navigation
    'nav.forRetailers': 'दुकानदारों के लिए',
    'nav.solutions': 'समाधान',
    'nav.products': 'प्रोडक्ट्स',
    'nav.resources': 'जानकारी',
    'nav.pricing': 'कीमतें',
    
    // Products Page
    'products.hero.titleLine1': 'ऐसी बिलिंग, जो आपके',
    'products.hero.titleLine1Part2Before': 'बिज़नेस को',
    'products.hero.titleLine1Part2After': 'सच में समझे',
    'products.hero.titleLine2': 'ल्यूम आपकी बिलिंग, ग्राहक जानकारी, कैम्पेन और एनालिटिक्स को',
    'products.hero.titleLine3': 'एक ही स्मार्ट रिटेल प्लेटफ़ॉर्म में जोड़ता है —',
    'products.hero.titleLine4': 'ताकि आपकी दुकान बेहतर चले, ग्राहक जुड़े रहें और बिक्री बढ़े।',
    'products.hero.bookDemo': 'डेमो बुक करें',
    'products.hero.seeFeatures': 'सभी फ़ीचर्स देखें',
    'products.whatIsLume.title': 'ल्यूम क्या है?',
    'products.whatIsLume.point1': 'ल्यूम एक पूरा रिटेल प्लेटफ़ॉर्म है, जो आपको सिर्फ बिल बनाने से आगे ले जाता है।',
    'products.whatIsLume.point2': 'यह आपके मौजूदा POS या वेब बिलिंग सिस्टम के साथ काम करता है, हर बिल को अपने-आप पढ़ता है और उस बिलिंग डेटा को ग्राहक समझ, लॉयल्टी और बिज़नेस ग्रोथ में बदल देता है।',
    'products.coreCapabilities.title': 'ल्यूम से आप क्या कर सकते हैं',
    'products.coreCapabilities.billing.title': 'बिलिंग और POS इंटीग्रेशन',
    'products.coreCapabilities.billing.desc': 'बिलिंग जो तेज़ भी है और लचीली भी',
    'products.coreCapabilities.billing.feature1': 'टैक्स और नॉन-टैक्स बिलिंग',
    'products.coreCapabilities.billing.feature2': 'क्विक बिलिंग और इमेज बिलिंग',
    'products.coreCapabilities.billing.feature3': 'अलग-अलग बिल टेम्पलेट',
    'products.coreCapabilities.billing.feature4': 'POS प्लग-इन (किसी भी मौजूदा POS से कनेक्ट करें)',
    'products.coreCapabilities.digitalBills.title': 'स्मार्ट डिजिटल बिल',
    'products.coreCapabilities.digitalBills.desc': 'हर बिल को ग्राहक से जुड़ने का ज़रिया बनाइए',
    'products.coreCapabilities.digitalBills.feature1': 'व्हाट्सऐप / SMS / ईमेल से बिल भेजें',
    'products.coreCapabilities.digitalBills.feature2': 'बिल के अंदर ऑफ़र और प्रमोशन',
    'products.coreCapabilities.digitalBills.feature3': 'फ़ीडबैक और गूगल रेटिंग लिंक',
    'products.coreCapabilities.digitalBills.feature4': 'सोशल शेयरिंग और रेफ़र एंड अर्न प्रोग्राम',
    'products.coreCapabilities.loyalty.title': 'ग्राहक और लॉयल्टी सिस्टम',
    'products.coreCapabilities.loyalty.desc': 'हर खरीद के साथ रिश्ते मज़बूत करें',
    'products.coreCapabilities.loyalty.feature1': 'ग्राहक अपने-आप जुड़ जाते हैं',
    'products.coreCapabilities.loyalty.feature2': 'पूरी खरीदारी हिस्ट्री',
    'products.coreCapabilities.loyalty.feature3': 'लॉयल्टी पॉइंट्स और कूपन',
    'products.coreCapabilities.loyalty.feature4': 'दोबारा आने वाले ग्राहकों की ट्रैकिंग',
    'products.coreCapabilities.analytics.title': 'एनालिटिक्स और रिपोर्ट्स',
    'products.coreCapabilities.analytics.desc': 'अब फैसले अनुमान से नहीं, डेटा से होंगे',
    'products.coreCapabilities.analytics.feature1': 'बिक्री और प्रोडक्ट एनालिटिक्स',
    'products.coreCapabilities.analytics.feature2': 'ग्राहक व्यवहार की जानकारी',
    'products.coreCapabilities.analytics.feature3': 'समय के हिसाब से इनसाइट्स',
    'products.coreCapabilities.analytics.feature4': 'डाउनलोड करने योग्य रिपोर्ट्स',
    'products.coreCapabilities.campaign.title': 'कैम्पेन मैनेजर',
    'products.coreCapabilities.campaign.desc': 'सही ग्राहक को, सही समय पर पहुँचिए',
    'products.coreCapabilities.campaign.feature1': 'ग्राहक सेगमेंट के हिसाब से कैम्पेन',
    'products.coreCapabilities.campaign.feature2': 'व्हाट्सऐप, SMS जैसे कई चैनल',
    'products.coreCapabilities.campaign.feature3': 'कैम्पेन परफॉर्मेंस ट्रैकिंग',
    'products.coreCapabilities.campaign.feature4': 'ऑटोमेटेड वर्कफ़्लो',
    'products.howItWorks.title': 'ल्यूम आपके बिज़नेस में कैसे फिट होता है',
    'products.howItWorks.step1.title': 'POS / वेब / प्लग-इन से बिल बनाएँ',
    'products.howItWorks.step1.desc': 'अपना मौजूदा सिस्टम इस्तेमाल करें या ल्यूम का वेब POS।',
    'products.howItWorks.step2.title': 'ल्यूम हर बिल का डेटा जोड़ता है',
    'products.howItWorks.step2.desc': 'हर ट्रांज़ैक्शन अपने-आप सेव और प्रोसेस होती है।',
    'products.howItWorks.step3.title': 'ग्राहक को स्मार्ट डिजिटल बिल मिलता है',
    'products.howItWorks.step3.desc': 'जिसमें ऑफ़र, फ़ीडबैक और ज़रूरी लिंक होते हैं।',
    'products.howItWorks.step4.title': 'डेटा से एनालिटिक्स, लॉयल्टी और कैम्पेन चलते हैं',
    'products.howItWorks.step4.desc': 'जिससे बेहतर फैसले और ज़्यादा ग्राहक जुड़ाव होता है।',
    'products.whoIsLumeFor.title': 'आपके साथ-साथ बढ़ने के लिए बना',
    'products.whoIsLumeFor.singleStore.title': 'सिंगल स्टोर रिटेलर',
    'products.whoIsLumeFor.singleStore.desc': 'जो अपनी दुकान को डिजिटल बनाना चाहते हैं',
    'products.whoIsLumeFor.multiStore.title': 'मल्टी-स्टोर बिज़नेस',
    'products.whoIsLumeFor.multiStore.desc': 'एक ही डैशबोर्ड से कई दुकानों का मैनेजमेंट',
    'products.whoIsLumeFor.growingChains.title': 'बढ़ती हुई रिटेल चेन',
    'products.whoIsLumeFor.growingChains.desc': 'एंटरप्राइज़-लेवल टूल्स के साथ स्केल करें',
    'products.lumeShop.title': 'ल्यूम शॉप के साथ ल्यूम को और आगे बढ़ाइए',
    'products.lumeShop.desc': 'ल्यूम शॉप आपकी दुकान को एक हाइपरलोकल ऑनलाइन स्टोर में बदल देता है। ऑर्डर, ग्राहक और डेटा — सब कुछ ल्यूम से जुड़ा रहता है।',
    'products.lumeShop.comingSoon': 'जल्द आ रहा है',
    'products.lumeShop.preview': 'ल्यूम शॉप प्रीव्यू',
    'products.trust.retailers': 'रिटेलर्स',
    'products.trust.transactions': 'ट्रांज़ैक्शन्स',
    'products.trust.rating': 'रेटिंग',
    'products.trust.growth': 'औसतन बिक्री में बढ़ोतरी',
    'products.trust.testimonial': 'ल्यूम ने हमारी दुकान संभालने का तरीका ही बदल दिया। अब सब कुछ एक-दूसरे से जुड़ा है।',
    'products.trust.testimonialAuthor': 'रिटेल स्टोर ओनर',
    'products.cta.title': 'ल्यूम को लाइव देखकर समझिए',
    'products.cta.bookDemo': 'डेमो बुक करें',
    'products.cta.viewPricing': 'प्राइसिंग देखें',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Get from localStorage or default to EN
    const saved = localStorage.getItem('language') as Language;
    return saved && (saved === 'EN' || saved === 'HI') ? saved : 'EN';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

