import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'EN' | 'HI';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  EN: {
    // Hero Section
    'hero.badge': 'Trusted by 285+ retailers across India',
    'hero.title': 'AI-First Retail Solutions that Turns Billing into Repeat Customers & Continuous Sales Growth',
    'hero.titleHighlight': '',
    'hero.titleHighlightLine1': '',
    'hero.titleHighlightLine2': '',
    'hero.titleHighlightPart1': '',
    'hero.titleHighlightPart2': '',
    'hero.titleHighlightBilling': '',
    'hero.titleHighlightCTA': '',
    'hero.description': 'Lume connects billing, customer data, campaigns, and analytics into one intelligent retail platform that works with your existing systems.',
    'hero.download': 'Download',
    'hero.watchDemo': 'Book a Demo',
    'hero.rating': '4.8/5 from 285+ reviews',

    // Hero Carousel - Slide 1: Retailer App
    'hero.slide1.tab': 'Retailer Growth App',
    'hero.slide1.badge': 'B2B RETAILER GROWTH ENGINE',
    'hero.slide1.title': 'AI-First Retail Solutions that Turn Billing into Repeat Customers & Continuous Sales Growth',
    'hero.slide1.desc': 'Lume connects POS billing, customer data, automated WhatsApp offers, and sales analytics into one intelligent growth engine for your store.',
    'hero.slide1.ctaPrimary': 'Download Retailer App',
    'hero.slide1.ctaSecondary': 'Book a Demo',
    'hero.slide1.pill1': '3-Sec Digital Bills',
    'hero.slide1.pill2': 'Auto Loyalty & Cashback',
    'hero.slide1.pill3': 'Sales Analytics',
    'hero.slide1.pill4': 'Credit & Debt Ledger',

    // Hero Carousel - Slide 2: Lume Shop Consumer App
    'hero.slide2.tab': 'Lume Shop Consumer App',
    'hero.slide2.badge': 'B2C HYPER-LOCAL SHOPPING APP',
    'hero.slide2.title': 'Shop Online from Nearby Stores with Instant Delivery via Lume Shop',
    'hero.slide2.desc': 'Discover trusted local retailers in your neighborhood (Grocery, Fashion, Electronics, Bakery). Order online at direct store prices with fast doorstep delivery.',
    'hero.slide2.ctaPrimary': 'Explore Lume Shop',
    'hero.slide2.ctaSecondary': 'List Your Store Free',
    'hero.slide2.pill1': 'Instant Delivery',
    'hero.slide2.pill2': 'Verified Nearby Stores',
    'hero.slide2.pill3': 'Direct Store Prices',
    'hero.slide2.pill4': 'Live Order Tracking',

    // Hero Carousel - Slide 3: Unified Ecosystem
    'hero.slide3.tab': 'Unified 360° Ecosystem',
    'hero.slide3.badge': 'RETAILER + CONSUMER NETWORK',
    'hero.slide3.title': 'Connecting Local Retailers & Nearby Customers into One Unified Growth Network',
    'hero.slide3.desc': 'When retailers bill on Lume POS, inventory syncs instantly to Lume Shop. Nearby customers buy online, driving 3x store reach and zero commission fees.',
    'hero.slide3.ctaPrimary': 'Join Lume Network',
    'hero.slide3.ctaSecondary': 'See How It Works',
    'hero.slide3.pill1': 'Live Stock Auto-Sync',
    'hero.slide3.pill2': '0% Extra Commission',
    'hero.slide3.pill3': '3x Sales Multiplier',
    'hero.slide3.pill4': 'Instant Local Delivery',

    // SEO H2 headings (unique, no duplicate)
    'seo.h2.whatIsLume': 'What is Lume Retail POS?',
    'seo.h2.smartBilling': 'Smart Billing Software for Indian Retailers',
    'seo.h2.customerInsights': 'Customer Insights & Sales Analytics',
    'seo.h2.digitalBillsLoyalty': 'Digital Bills, Loyalty & Marketing Tools',
    'seo.h2.whyChooseLume': 'Why Indian Retailers Choose Lume',
    'seo.h2.keyFeatures': 'Key Features of Lume POS Platform',
    'seo.h2.useCases': 'Use Cases for Retail Stores',
    'seo.h2.faq': 'Frequently Asked Questions',
    'seo.link.exploreFeatures': 'Explore POS Features',
    'seo.link.viewAnalytics': 'View Customer Analytics',
    'seo.link.seeDemo': 'See Digital Billing Demo',
    'seo.link.checkPricing': 'Check Pricing Plans',
    
    // Stats
    'stats.retailers': 'Retailers Trust Us',
    'stats.transactions': 'Transactions Processed',
    'stats.revenue': 'Average Revenue Increase',
    'stats.rating': 'Customer Rating',
    
    // Challenge Section
    'challenge.title': 'Why Local Retailers Are Losing Customers',
    'challenge.subtitle': 'Customer expectations are changing faster than ever.',
    'challenge.point1': 'Customers expect instant convenience',
    'challenge.point1Sub': 'Fast delivery and smooth shopping are now the norm.',
    'challenge.point2': 'Slow billing hurts sales',
    'challenge.point2Sub': 'Long queues and delays impact customer experience.',
    'challenge.point3': 'Hard to retain repeat customers',
    'challenge.point3Sub': 'Without engagement, loyal buyers are hard to keep.',
    'challenge.point4': 'Limited visibility into sales',
    'challenge.point4Sub': 'No clear insights makes growth harder to manage.',
    'challenge.solution': 'More than billing. A complete digital system for your store.',
    'challenge.solutionDesc': 'Lume connects billing, customers, offers, stock and insights into one simple retail intelligence platform.',
    'challenge.supportLine': '',
    'challenge.cta': 'Book a Demo',
    
    // Benefits
    'benefit.fastBilling.title': 'Fast & Easy Billing',
    'benefit.fastBilling.desc': 'Make bills in seconds—tax or non-tax, with image billing and simple templates. Less waiting, smoother checkout, happier customers.',
    'benefit.posIntegration.title': 'Works with Your Current POS',
    'benefit.posIntegration.desc': 'Use Lume with your existing POS system. No need to change machines—Lume reads all your bills in one place.',
    'benefit.engagement.title': 'Every Bill Helps You Get More Sales',
    'benefit.engagement.desc': 'Each bill can send offers, loyalty points, feedback links, and Google rating requests automatically. Customers remember your store and come back again.',
    'benefit.customerCapture.title': 'Customer Details Get Saved Automatically',
    'benefit.customerCapture.desc': 'Every bill saves who bought, what they bought, and when they bought it. Over time, you understand your customers better without extra work.',
    'benefit.smartOffers.title': 'Smart Offers That Increase Bill Value',
    'benefit.smartOffers.desc': 'Give the right offer at the right time—like tea with milk or related items with clothes. This helps customers buy more in the same visit.',
    'benefit.dashboard.title': 'See Your Business in One Screen',
    'benefit.dashboard.desc': 'Check sales, stock, customers, and offers from one simple dashboard. You always know how your shop is doing.',
    'featuresSection.title': 'Built to Simplify Every Part of Your Store',
    'featuresSection.subtitle': 'From faster billing to smarter offers and customer insights — everything works together.',
    
    // How It Works
    'howItWorks.title': 'Start Selling Smarter in 4 Simple Steps',
    'howItWorks.subtitle': 'Get started in minutes and transform your retail business',
    'howItWorks.step1.title': 'Download the App',
    'howItWorks.step1.desc': 'Free download from Play Store. Setup takes just 5 minutes.',
    'howItWorks.step2.title': 'Add Your Products',
    'howItWorks.step2.desc': 'Scan barcodes or add manually. Bulk import available.',
    'howItWorks.step3.title': 'Start Billing',
    'howItWorks.step3.desc': 'Create digital bills and capture customer data automatically.',
    'howItWorks.step4.title': 'Grow Your Business',
    'howItWorks.step4.desc': 'Use insights and engagement tools to increase repeat customers.',
    'howItWorks.cta': 'Book a Demo',
    
    // Industries
    'industries.title': 'Built for All Types of Retail Stores',
    'industries.subtitle': 'Trusted by thousands of retailers across different industries. Lume works seamlessly for every type of store.',
    'industries.grocery': 'Grocery & Kirana Stores',
    'industries.fashion': 'Fashion & Apparel Stores',
    'industries.electronics': 'Electronics & Mobile Stores',
    'industries.pharmacy': 'Pharmacy & Medical Stores',
    'industries.general': 'General Stores',
    'industries.footwear': 'Footwear Stores',
    'industries.cosmetic': 'Cosmetic & Beauty Stores',
    'industries.stationery': 'Stationery & Book Stores',
    'industries.hardware': 'Hardware & Electrical Stores',
    'industries.bakery': 'Bakery & Sweet Shops',
    
    // Testimonials
    'testimonials.quote': 'Retailers Love Lume',
    'testimonials.subtitle': 'Join thousands of store owners who have transformed their business with Lume.',
    
    // Final CTA
    'cta.title': 'Ready to Grow Your Retail Business?',
    'cta.description': 'Join 285+ retailers who trust Lume. Book a demo today to see how it works.',
    'cta.startTrial': 'Book a Demo',
    'cta.contactSales': 'Contact Sales',
    
    // Products Page
    'products.hero.titleLine1': 'Billing that understands',
    'products.hero.titleLine2': 'your business',
    'products.hero.subtitle': 'Lume connects billing, customer data, campaigns, and analytics into a single retail intelligence platform.',
    'products.hero.bookDemo': 'Book a Demo',
    'products.hero.seeFeatures': 'See Features',
    'products.whatIsLume.title': 'What is Lume?',
    'products.whatIsLume.point1': 'Lume is a complete retail platform that helps you move beyond basic billing.',
    'products.whatIsLume.point2': 'It works with your existing POS or web billing system, reads every bill automatically, and converts billing data into customer insights, loyalty, and growth tools.',
    'products.coreCapabilities.title': 'What You Can Do With Lume',
    'products.coreCapabilities.billing.title': 'Billing & POS Integration',
    'products.coreCapabilities.billing.desc': 'Seamless billing with flexible integration options',
    'products.coreCapabilities.billing.feature1': 'Tax & non-tax billing',
    'products.coreCapabilities.billing.feature2': 'Quick billing & image billing',
    'products.coreCapabilities.billing.feature3': 'Multiple billing templates',
    'products.coreCapabilities.billing.feature4': 'POS plugin (connect any existing POS)',
    'products.coreCapabilities.digitalBills.title': 'Smart Digital Bills',
    'products.coreCapabilities.digitalBills.desc': 'Transform bills into customer engagement tools',
    'products.coreCapabilities.digitalBills.feature1': 'WhatsApp / SMS / Email bills',
    'products.coreCapabilities.digitalBills.feature2': 'Promotions inside bills',
    'products.coreCapabilities.digitalBills.feature3': 'Feedback & Google rating',
    'products.coreCapabilities.digitalBills.feature4': 'Social sharing & refer & earn',
    'products.coreCapabilities.loyalty.title': 'Customer & Loyalty Engine',
    'products.coreCapabilities.loyalty.desc': 'Build stronger relationships with every purchase',
    'products.coreCapabilities.loyalty.feature1': 'Auto customer capture',
    'products.coreCapabilities.loyalty.feature2': 'Complete purchase history',
    'products.coreCapabilities.loyalty.feature3': 'Loyalty points & coupons',
    'products.coreCapabilities.loyalty.feature4': 'Repeat customer tracking',
    'products.coreCapabilities.analytics.title': 'Analytics & Reports',
    'products.coreCapabilities.analytics.desc': 'Make decisions based on data, not guesswork',
    'products.coreCapabilities.analytics.feature1': 'Sales & product analytics',
    'products.coreCapabilities.analytics.feature2': 'Customer behavior insights',
    'products.coreCapabilities.analytics.feature3': 'Time-based insights',
    'products.coreCapabilities.analytics.feature4': 'Downloadable reports',
    'products.coreCapabilities.campaign.title': 'Campaign Manager',
    'products.coreCapabilities.campaign.desc': 'Reach the right customers at the right time',
    'products.coreCapabilities.campaign.feature1': 'Segmented campaigns',
    'products.coreCapabilities.campaign.feature2': 'Multiple channels',
    'products.coreCapabilities.campaign.feature3': 'Campaign performance tracking',
    'products.coreCapabilities.campaign.feature4': 'Automated workflows',
    'products.howItWorks.title': 'How Lume Fits Into Your Business',
    'products.howItWorks.step1.title': 'Bill from POS / Web / Plugin',
    'products.howItWorks.step1.desc': 'Use your existing system or Lume\'s web POS. Bill as usual.',
    'products.howItWorks.step2.title': 'Lume reads and unifies all bill data',
    'products.howItWorks.step2.desc': 'Every transaction is automatically captured and processed.',
    'products.howItWorks.step3.title': 'Smart bill goes to customer',
    'products.howItWorks.step3.desc': 'Digital bills with promotions, feedback links, and more.',
    'products.howItWorks.step4.title': 'Data powers analytics, loyalty & campaigns',
    'products.howItWorks.step4.desc': 'Insights drive better decisions and customer engagement.',
    'products.whoIsLumeFor.title': 'Built to Scale With You',
    'products.whoIsLumeFor.singleStore.title': 'Single store retailers',
    'products.whoIsLumeFor.singleStore.desc': 'Perfect for individual stores looking to digitize operations',
    'products.whoIsLumeFor.multiStore.title': 'Multi-store businesses',
    'products.whoIsLumeFor.multiStore.desc': 'Manage multiple locations with unified data and insights',
    'products.whoIsLumeFor.growingChains.title': 'Growing retail chains',
    'products.whoIsLumeFor.growingChains.desc': 'Scale your operations with enterprise-grade tools',
    'products.lumeShop.title': 'Extend Lume With Lume Shop',
    'products.lumeShop.desc': 'Lume Shop lets you turn your retail store into a hyperlocal online store. Orders, customers, and data stay connected with Lume.',
    'products.lumeShop.comingSoon': 'Coming Soon',
    'products.lumeShop.preview': 'Lume Shop Preview',
    'products.trust.retailers': 'Retailers',
    'products.trust.transactions': 'Transactions',
    'products.trust.rating': 'Rating',
    'products.trust.growth': 'Average Sales Growth',
    'products.trust.testimonial': 'Lume changed how we manage our store. Everything is connected now.',
    'products.trust.testimonialAuthor': 'Retail Store Owner',
    'products.cta.title': 'Ready to See Lume in Action?',
    'products.cta.bookDemo': 'Book a Demo',
    'products.cta.viewPricing': 'View Pricing',

    // Products page FAQ
    'products.faq.title': 'Frequently Asked Questions',
    'products.faq.q1': 'What is Lume?',
    'products.faq.a1': 'Lume is a digital billing, customer engagement and marketing platform for Indian retailers. It turns every bill into a digital receipt on WhatsApp, captures customer data automatically, and helps you run loyalty programs and marketing campaigns to bring customers back.',
    'products.faq.q2': 'What are digital bills and how are they different from paper receipts?',
    'products.faq.a2': 'A digital bill is a paperless version of your invoice, sent instantly to the customer on WhatsApp, SMS or email instead of printing a paper receipt. It captures the customer’s contact details automatically, so every sale also builds your customer list.',
    'products.faq.q3': 'Can I run marketing campaigns with Lume?',
    'products.faq.a3': 'Yes. Lume’s Campaign Manager lets you send offers, discounts and festive greetings to customers captured from digital bills, so you can run targeted marketing campaigns without a separate tool.',
    'products.faq.q4': 'How does Lume help bring repeat customers back?',
    'products.faq.a4': 'Lume combines digital bills, loyalty coupons and WhatsApp campaigns so customers who bought once are automatically eligible for offers that bring them back, turning one-time buyers into repeat customers over time.',
    'products.faq.q5': 'Do I need to change my existing billing or POS setup to use Lume?',
    'products.faq.a5': 'No. You can bill directly inside Lume, or connect your existing POS/billing setup so digital bills, customer data and analytics flow into one place without changing how you currently bill.',

    // Header Navigation
    'nav.forRetailers': 'For Retailers',
    'nav.solutions': 'Solutions',
    'nav.industries': 'Category',
    'nav.features': 'Features',
    'nav.products': 'Products',
    'nav.resources': 'Resources',
    'nav.pricing': 'Pricing',
    'nav.financials': 'Financials',
    'nav.bookDemo': 'Book a Demo',

    // Financials Page
    'financials.title': 'Financials',

    // Footer
    'footer.tagline': 'We turn billing into a growth engine for retailers.',
    'footer.company': 'Company',
    'footer.products': 'Products',
    'footer.solutions': 'Solutions',
    'footer.resources': 'Resources',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.investors': 'Investors',
    'footer.contact': 'Contact',
    'footer.webPos': 'Web POS – Online Billing',
    'footer.posPlugin': 'POS Plugin – Add‑on for Billing',
    'footer.analytics': 'Analytics Dashboard',
    'footer.campaign': 'Campaign Manager',
    'footer.lume': 'Lume',
    'footer.mpos': 'MPos – Mobile POS',
    'footer.lumeShopComingSoon': 'Lume Shop (Coming Soon)',
    'footer.smartBilling': 'Smart Billing',
    'footer.digitalBills': 'Digital Bills on WhatsApp',
    'footer.customerAnalytics': 'Customer Analytics',
    'footer.loyalty': 'Loyalty & Coupons',
    'footer.campaignManagement': 'Campaign Management',
    'footer.pricing': 'Pricing',
    'footer.caseStudies': 'Case Studies',
    'footer.blog': 'Blog',
    'footer.guides': 'Guides',
    'footer.helpCenter': 'Help Center',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.copyright': 'All rights reserved.',
    
    // Book Demo Page
    'demo.title': 'Book a Demo',
    'demo.subtitle': 'See how Lume can transform your retail business. Schedule a personalized demo with our team.',
    'demo.formTitle': 'Schedule Your Demo',
    'demo.name': 'Full Name',
    'demo.namePlaceholder': 'Enter your full name',
    'demo.phone': 'Phone Number',
    'demo.phonePlaceholder': 'Enter your phone number',
    'demo.email': 'Email Address',
    'demo.emailPlaceholder': 'Enter your email address',
    'demo.selectDate': 'Select Date',
    'demo.selectTime': 'Select Time Slot',
    'demo.submit': 'Book Demo',
    'demo.successTitle': 'Demo Booked Successfully!',
    'demo.successMessage': 'We\'ll send you a confirmation email with the meeting details shortly.',
    'demo.whatToExpect': 'What to Expect',
    'demo.expect1': 'Live walkthrough of all features',
    'demo.expect2': 'See how it works for your store type',
    'demo.expect3': 'Get answers to all your questions',
    'demo.expect4': 'Learn about pricing and setup',
    'demo.officeHours': 'Office Hours',
    'demo.weekdays': 'Monday - Friday',
    'demo.weekend': 'Saturday & Sunday',
    'demo.closed': 'Closed',
    'demo.today': 'Today',
    'demo.tomorrow': 'Tomorrow',
    'demo.dayAfter': 'Day After',

    // Quick Inquiry Popup
    'quickInquiry.title': "Let's Get Started 👋",
    'quickInquiry.subtitle': "Leave your contact details and our team will get in touch with you shortly.",
    'quickInquiry.namePlaceholder': 'Your Name',
    'quickInquiry.phonePlaceholder': 'Mobile Number',
    'quickInquiry.emailPlaceholder': 'Email Address (Optional)',
    'quickInquiry.submit': 'Get Started',
    'quickInquiry.disclaimer': "No spam. We'll only contact you regarding your enquiry.",
    'quickInquiry.successTitle': 'Thanks for reaching out!',
    'quickInquiry.successMessage': 'Our team will get in touch with you shortly.',
    'quickInquiry.errorMessage': 'Something went wrong. Please try again.',

    // For Retailers Page
    'forRetailers.hero.badge': 'Rated 4.8/5 by 285+ retailers',
    'forRetailers.hero.title': 'Turn Your Store into a',
    'forRetailers.hero.titleHighlight': 'Modern Business',
    'forRetailers.hero.description': 'Lume gives you everything you need to compete with quick commerce — digital billing, customer insights, and smart tools that work on any phone.',
    'forRetailers.hero.bookDemo': 'Book a Demo',
    'forRetailers.hero.viewPricing': 'View Pricing',
    
    'forRetailers.problems.title': 'Your Problems, Solved',
    'forRetailers.problems.subtitle': 'We built Lume for the real challenges Indian retailers face every day.',
    'forRetailers.problems.problem1': 'Manual billing wastes hours daily',
    'forRetailers.problems.solution1': 'Digital bills in under 10 seconds',
    'forRetailers.problems.problem2': 'No customer data or repeat buyers',
    'forRetailers.problems.solution2': 'Auto-capture customer info & history',
    'forRetailers.problems.problem3': 'Credit (udhaar) leads to losses',
    'forRetailers.problems.solution3': 'Smart tracking & auto-reminders',
    'forRetailers.problems.problem4': 'Can\'t track real profit margins',
    'forRetailers.problems.solution4': 'Real-time analytics dashboard',
    'forRetailers.problems.problem5': 'Customers forget your store',
    'forRetailers.problems.solution5': 'Automated WhatsApp offers',
    
    'forRetailers.howItWorks.title': 'Go Digital in 3 Easy Steps',
    'forRetailers.howItWorks.step1.title': 'Download & Setup',
    'forRetailers.howItWorks.step1.description': 'Download from Play Store. Add your store details and products in minutes.',
    'forRetailers.howItWorks.step1.time': '5 minutes',
    'forRetailers.howItWorks.step2.title': 'Start Billing',
    'forRetailers.howItWorks.step2.description': 'Create professional GST bills instantly. Customer data captured automatically.',
    'forRetailers.howItWorks.step2.time': '10 seconds/bill',
    'forRetailers.howItWorks.step3.title': 'Grow Revenue',
    'forRetailers.howItWorks.step3.description': 'Use insights & engagement tools to bring customers back and increase sales.',
    'forRetailers.howItWorks.step3.time': '25% avg. growth',
    
    'forRetailers.industries.title': 'Built for Your Type of Store',
    'forRetailers.industries.subtitle': 'Whether you sell groceries, fashion, or electronics — Lume adapts to your business.',
    'forRetailers.industries.grocery.name': 'Grocery & Kirana',
    'forRetailers.industries.grocery.description': 'Inventory tracking, expiry alerts, supplier management',
    'forRetailers.industries.fashion.name': 'Fashion & Apparel',
    'forRetailers.industries.fashion.description': 'Size/color variants, seasonal sales, loyalty programs',
    'forRetailers.industries.electronics.name': 'Electronics',
    'forRetailers.industries.electronics.description': 'Warranty tracking, service reminders, high-value billing',
    'forRetailers.industries.general.name': 'General Stores',
    'forRetailers.industries.general.description': 'Multi-category management, flexible pricing, credit tracking',
    
    'forRetailers.testimonials.title': 'Real Results from Real Retailers',
    'forRetailers.testimonials.story1.metric': '40%',
    'forRetailers.testimonials.story1.outcome': 'increase in repeat customers',
    'forRetailers.testimonials.story1.quote': 'My customers now get WhatsApp bills. They love it and keep coming back.',
    'forRetailers.testimonials.story1.name': 'Vijay Grocery',
    'forRetailers.testimonials.story2.metric': '₹50K',
    'forRetailers.testimonials.story2.outcome': 'saved in bad debts monthly',
    'forRetailers.testimonials.story2.quote': 'The credit tracking feature has transformed how I manage udhaar.',
    'forRetailers.testimonials.story2.name': 'Style Corner',
    'forRetailers.testimonials.story3.metric': '2 hours',
    'forRetailers.testimonials.story3.outcome': 'saved daily on billing',
    'forRetailers.testimonials.story3.quote': 'What took hours now takes minutes. I can focus on customers.',
    'forRetailers.testimonials.story3.name': 'City Mart',
    
    'forRetailers.roi.title': 'Lume Pays for Itself in the First Month',
    'forRetailers.roi.description': 'Our retailers see measurable ROI within weeks of starting. Here\'s what you can expect:',
    'forRetailers.roi.timeSaved.value': '2 hours/day',
    'forRetailers.roi.timeSaved.label': 'Time saved on billing',
    'forRetailers.roi.creditRecovered.value': '₹15,000/month',
    'forRetailers.roi.creditRecovered.label': 'Credit recovered',
    'forRetailers.roi.repeatCustomers.value': '30% increase',
    'forRetailers.roi.repeatCustomers.label': 'More repeat customers',
    'forRetailers.roi.averageROI.value': '10x return on investment',
    'forRetailers.roi.averageROI.label': 'Average ROI',
    
    'forRetailers.testimonials.story1.location': 'Ahmedabad',
    'forRetailers.testimonials.story2.location': 'Mumbai',
    'forRetailers.testimonials.story3.location': 'Thane',
    
    'forRetailers.cta.title': 'Ready to Get Started?',
    'forRetailers.cta.feature1': 'Live demo with all features',
    'forRetailers.cta.feature2': 'No credit card required',
    'forRetailers.cta.feature3': 'Free onboarding support',
    'forRetailers.cta.feature4': 'Works on any Android phone',
    'forRetailers.cta.feature5': 'Cancel anytime, no questions asked',
    'forRetailers.cta.bookDemo': 'Book a Demo',
    'forRetailers.cta.viewPricing': 'Or view pricing plans',
  },
  HI: {
    // Hero Section (SEO: short sentences, unique Hindi)
    'hero.badge': 'भारत के 285+ दुकानदारों का भरोसा',
    'hero.title': 'ग्राहक को वापस लाने',
    'hero.titleHighlight': 'सॉफ्टवेयर नहीं',
    'hero.titleHighlightLine1': 'वाला सिस्टम सिर्फ बिलिंग',
    'hero.titleHighlightLine2': 'सॉफ्टवेयर नहीं',
    'hero.titleHighlightPart1': 'वाला सिस्टम सिर्फ बिलिंग',
    'hero.titleHighlightPart2': 'सॉफ्टवेयर नहीं',
    'hero.titleHighlightBilling': '',
    'hero.titleHighlightCTA': '',
    'hero.description': 'हर बिल पर कैशबैक, पॉइंट्स और स्मार्ट ऑफर मिलते ही ग्राहक दोबारा आता है और ज़्यादा खरीदता है। जो नहीं आ रहा उसे बुलाओ, जो आ रहा है उसका बिल बढ़ाओ — ऑटोमैटिक।',
    'hero.download': 'डाउनलोड करें',
    'hero.watchDemo': 'डेमो बुक करें',
    'hero.rating': '4.8/5 रेटिंग (285+ दुकानदारों की राय)',

    // Hero Carousel - Slide 1: Retailer App (Hindi)
    'hero.slide1.tab': 'रिटेलर ग्रोथ ऐप',
    'hero.slide1.badge': 'B2B रिटेलर ग्रोथ इंजन',
    'hero.slide1.title': 'अपनी दुकान को बनाओ स्मार्ट ग्रोइंग बिज़नेस - ग्राहक बार-बार वापस आएँगे!',
    'hero.slide1.desc': 'ल्यूम बिलिंग, कस्टमर डेटा, ऑटोमैटिक व्हाट्सऐप ऑफर्स, और सेल्स एनालिटिक्स को जोड़कर आपकी दुकान की बिक्री लगातार बढ़ाता है।',
    'hero.slide1.ctaPrimary': 'रिटेलर ऐप डाउनलोड करें',
    'hero.slide1.ctaSecondary': 'डेमो बुक करें',
    'hero.slide1.pill1': '3-सेकंड डिजिटल बिल',
    'hero.slide1.pill2': 'ऑटो लॉयल्टी व कैशबैक',
    'hero.slide1.pill3': 'सेल्स एनालिटिक्स',
    'hero.slide1.pill4': 'उधार व क्रेडिट खाता',

    // Hero Carousel - Slide 2: Lume Shop Consumer App (Hindi)
    'hero.slide2.tab': 'ल्यूम शॉप कस्टमर ऐप',
    'hero.slide2.badge': 'B2C लोकल शॉपिंग ऐप',
    'hero.slide2.title': 'अपने पास की भरोसेमंद दुकानों से ऑनलाइन मँगवाएँ - तेज़ इन्स्टेंट डिलीवरी!',
    'hero.slide2.desc': 'अपने आस-पास की किराना, फै़शन, बेकरी और इलेक्ट्रॉनिक्स दुकानों से ल्यूम शॉप ऐप के ज़रिए सीधे दुकान के रेट पर ख़रीदारी करें।',
    'hero.slide2.ctaPrimary': 'ल्यूम शॉप एक्सप्लोर करें',
    'hero.slide2.ctaSecondary': 'अपनी दुकान फ़्री जोड़ें',
    'hero.slide2.pill1': 'इन्स्टेंट होम डिलीवरी',
    'hero.slide2.pill2': 'पास की वेरीफाइड दुकानें',
    'hero.slide2.pill3': 'सीधे दुकान के रेट',
    'hero.slide2.pill4': 'लाइव ऑर्डर ट्रैकिंग',

    // Hero Carousel - Slide 3: Unified Ecosystem (Hindi)
    'hero.slide3.tab': 'कंप्लीट 360° इकोसिस्टम',
    'hero.slide3.badge': 'दुकानदार व ग्राहक नेटवर्क',
    'hero.slide3.title': 'दुकानदार की ऑनलाइन बिक्री और ग्राहक की आसान ख़रीदारी - एक ही प्लेटफ़ॉर्म पर!',
    'hero.slide3.desc': 'दुकानदार के ल्यूम POS पर बिल बनते ही सामान ऑनलाइन ल्यूम शॉप पर दिखने लगता है। पास के ग्राहक ऑनलाइन ऑर्डर करते हैं और बिक्री 3 गुना बढ़ती है।',
    'hero.slide3.ctaPrimary': 'ल्यूम नेटवर्क से जुड़ें',
    'hero.slide3.ctaSecondary': 'देखें कैसे काम करता है',
    'hero.slide3.pill1': 'लाइव स्टॉक ऑटो-सिंक',
    'hero.slide3.pill2': '0% अतिरिक्त कमीशन',
    'hero.slide3.pill3': '3 गुना ज़्यादा बिक्री',
    'hero.slide3.pill4': 'लोकल इन्स्टेंट डिलीवरी',

    // SEO H2 headings (Hindi – unique)
    'seo.h2.whatIsLume': 'ल्यूम रिटेल POS क्या है?',
    'seo.h2.smartBilling': 'भारतीय रिटेलर्स के लिए स्मार्ट बिलिंग सॉफ्टवेयर',
    'seo.h2.customerInsights': 'कस्टमर इनसाइट्स और सेल्स एनालिटिक्स',
    'seo.h2.digitalBillsLoyalty': 'डिजिटल बिल, लॉयल्टी और मार्केटिंग टूल्स',
    'seo.h2.whyChooseLume': 'भारतीय रिटेलर्स ल्यूम क्यों चुनते हैं',
    'seo.h2.keyFeatures': 'ल्यूम POS प्लेटफ़ॉर्म की मुख्य सुविधाएँ',
    'seo.h2.useCases': 'रिटेल स्टोर्स के लिए यूज़ केस',
    'seo.h2.faq': 'अक्सर पूछे जाने वाले सवाल',
    'seo.link.exploreFeatures': 'POS फीचर्स देखें',
    'seo.link.viewAnalytics': 'कस्टमर एनालिटिक्स देखें',
    'seo.link.seeDemo': 'डिजिटल बिलिंग डेमो देखें',
    'seo.link.checkPricing': 'प्लान और कीमत देखें',
    
    // Stats
    'stats.retailers': 'दुकानदार जुड़े हुए',
    'stats.transactions': 'का लेन-देन',
    'stats.revenue': 'बिज़नेस ग्रोथ',
    'stats.rating': 'कस्टमर रेटिंग',
    
    // Challenge Section
    'challenge.title': 'लोकल दुकानदार ग्राहक क्यों खो रहे हैं?',
    'challenge.subtitle': 'ग्राहक की उम्मीदें पहले से कहीं तेजी से बदल रही हैं।',
    'challenge.point1': 'ग्राहक तुरंत आसानी और सुविधा चाहते हैं',
    'challenge.point1Sub': 'तेज़ होम डिलीवरी और आसान शॉपिंग अब आम बात हो चुकी है।',
    'challenge.point2': 'धीमी बिलिंग से बिक्री का नुकसान',
    'challenge.point2Sub': 'काउंटर पर लंबी लाइनें और देरी ग्राहकों का अनुभव ख़राब करती हैं।',
    'challenge.point3': 'पुराने ग्राहकों को वापस लाना मुश्किल',
    'challenge.point3Sub': 'ऑफ़र और एंगेजमेंट के बिना वफ़ादार खरीदार वापस नहीं आते।',
    'challenge.point4': 'दुकान की बिक्री और मुनाफ़े की सही जानकारी नहीं',
    'challenge.point4Sub': 'हिसाब-किताब की कमी से बिज़नेस की तरक्की रुक जाती है।',
    'challenge.solution': 'अब सिर्फ बिलिंग नहीं — पूरी दुकान डिजिटल।',
    'challenge.solutionDesc': 'ल्यूम आपके बिल, ग्राहक, ऑफ़र, स्टॉक और रिपोर्ट्स को एक आसान सिस्टम में बदल देता है।',
    'challenge.supportLine': 'बिना महंगे मशीन • बिना टेक्निकल झंझट',
    'challenge.cta': 'डेमो बुक करें',
    
    // Benefits
    'benefit.fastBilling.title': 'तेज़ और आसान बिलिंग',
    'benefit.fastBilling.desc': 'स्मार्ट बिलिंग के साथ बिक्री एनालिटिक्स। सेकंड्स में बिल, कम इंतज़ार।',
    'benefit.posIntegration.title': 'आपके मौजूदा POS के साथ काम करता है',
    'benefit.posIntegration.desc': 'नई मशीन लेने की जरूरत नहीं। ल्यूम आपके पुराने सिस्टम के साथ भी चलता है।',
    'benefit.engagement.title': 'हर बिल से दोबारा बिक्री',
    'benefit.engagement.desc': 'हर बिल के साथ ऑफर, पॉइंट्स, फीडबैक और गूगल रेटिंग अपने आप चली जाती है। ग्राहक आपको याद रखता है।',
    'benefit.customerCapture.title': 'ग्राहक की जानकारी अपने आप सेव',
    'benefit.customerCapture.desc': 'किसने क्या खरीदा, कब खरीदा — सब रिकॉर्ड हो जाता है, बिना अलग मेहनत के।',
    'benefit.smartOffers.title': 'स्मार्ट ऑफर जो बिल बढ़ाए',
    'benefit.smartOffers.desc': 'सही समय पर सही ऑफर — जैसे चाय के साथ बिस्किट, कपड़ों के साथ मैचिंग आइटम।',
    'benefit.dashboard.title': 'पूरी दुकान एक स्क्रीन पर',
    'benefit.dashboard.desc': 'ग्राहकों की जानकारी और स्टोर परफॉर्मेंस रिपोर्ट एक ही डैशबोर्ड में।',
    'featuresSection.title': 'आपकी दुकान के हर काम को आसान बनाने के लिए निर्मित',
    'featuresSection.subtitle': 'तेज़ बिलिंग से लेकर स्मार्ट ऑफ़र और रिपोर्ट तक — सब कुछ एक साथ काम करता है।',
    
    // How It Works
    'howItWorks.title': '4 आसान स्टेप में शुरुआत',
    'howItWorks.subtitle': 'मिनटों में शुरू करें और अपने दुकान के बिज़नेस को बदलें',
    'howItWorks.step1.title': 'ऐप डाउनलोड करें',
    'howItWorks.step1.desc': 'Play Store से — 5 मिनट में सेटअप',
    'howItWorks.step2.title': 'प्रोडक्ट जोड़ें',
    'howItWorks.step2.desc': 'बारकोड स्कैन या मैन्युअली',
    'howItWorks.step3.title': 'बिलिंग शुरू करें',
    'howItWorks.step3.desc': 'डिजिटल बिल और ग्राहक डेटा अपने आप',
    'howItWorks.step4.title': 'बिज़नेस बढ़ाइए',
    'howItWorks.step4.desc': 'रिपोर्ट और ऑफर के साथ',
    'howItWorks.cta': 'डेमो बुक करें',
    
    // Industries
    'industries.title': 'सभी तरह की दुकानों के लिए बनाया गया',
    'industries.subtitle': 'हजारों दुकानदारों का भरोसा। ल्यूम हर तरह की दुकान के लिए काम करता है।',
    'industries.grocery': 'किराना एवं जनरल स्टोर',
    'industries.fashion': 'कपड़े एवं रेडीमेड स्टोर',
    'industries.electronics': 'इलेक्ट्रॉनिक्स एवं मोबाइल स्टोर',
    'industries.pharmacy': 'फार्मेसी एवं मेडिकल स्टोर',
    'industries.general': 'जनरल स्टोर',
    'industries.footwear': 'जूते एवं फुटवियर स्टोर',
    'industries.cosmetic': 'कॉस्मेटिक एवं ब्यूटी स्टोर',
    'industries.stationery': 'स्टेशनरी एवं बुक स्टोर',
    'industries.hardware': 'हार्डवेयर एवं इलेक्ट्रिकल स्टोर',
    'industries.bakery': 'बेकरी एवं मिठाई की दुकान',
    
    // Testimonials
    'testimonials.quote': 'दुकानदार ल्यूम से प्यार करते हैं',
    'testimonials.subtitle': 'हजारों दुकान मालिकों के साथ जुड़ें जिन्होंने ल्यूम के साथ अपने बिज़नेस को बदल दिया है।',
    
    // Final CTA
    'cta.title': 'अपने दुकान के बिज़नेस को बढ़ाने के लिए तैयार हैं?',
    'cta.description': '285+ दुकानदारों के साथ जुड़ें जो ल्यूम पर भरोसा करते हैं। आज ही डेमो बुक करें और देखें कि यह कैसे काम करता है।',
    'cta.startTrial': 'डेमो बुक करें',
    'cta.contactSales': 'सेल्स से संपर्क करें',
    
    // Book Demo Page
    'demo.title': 'डेमो बुक करें',
    'demo.subtitle': 'देखें कि ल्यूम आपके दुकान के बिज़नेस को कैसे बदल सकता है। हमारी टीम के साथ एक व्यक्तिगत डेमो शेड्यूल करें।',
    'demo.formTitle': 'अपना डेमो शेड्यूल करें',
    'demo.name': 'पूरा नाम',
    'demo.namePlaceholder': 'अपना पूरा नाम दर्ज करें',
    'demo.phone': 'फोन नंबर',
    'demo.phonePlaceholder': 'अपना फोन नंबर दर्ज करें',
    'demo.email': 'ईमेल पता',
    'demo.emailPlaceholder': 'अपना ईमेल पता दर्ज करें',
    'demo.selectDate': 'तारीख चुनें',
    'demo.selectTime': 'समय स्लॉट चुनें',
    'demo.submit': 'डेमो बुक करें',
    'demo.successTitle': 'डेमो सफलतापूर्वक बुक हो गया!',
    'demo.successMessage': 'हम आपको जल्द ही मीटिंग विवरण के साथ एक पुष्टिकरण ईमेल भेजेंगे।',
    'demo.whatToExpect': 'क्या उम्मीद करें',
    'demo.expect1': 'सभी सुविधाओं का लाइव डेमो',
    'demo.expect2': 'देखें कि यह आपके दुकान के प्रकार के लिए कैसे काम करता है',
    'demo.expect3': 'अपने सभी सवालों के जवाब पाएं',
    'demo.expect4': 'कीमत और सेटअप के बारे में जानें',
    'demo.officeHours': 'कार्यालय समय',
    'demo.weekdays': 'सोमवार - शुक्रवार',
    'demo.weekend': 'शनिवार और रविवार',
    'demo.closed': 'बंद',
    'demo.today': 'आज',
    'demo.tomorrow': 'कल',
    'demo.dayAfter': 'परसों',

    // Quick Inquiry Popup
    'quickInquiry.title': 'चलिए शुरू करते हैं 👋',
    'quickInquiry.subtitle': 'अपनी संपर्क जानकारी दें, हमारी टीम जल्द ही आपसे संपर्क करेगी।',
    'quickInquiry.namePlaceholder': 'आपका नाम',
    'quickInquiry.phonePlaceholder': 'मोबाइल नंबर',
    'quickInquiry.emailPlaceholder': 'ईमेल पता (वैकल्पिक)',
    'quickInquiry.submit': 'शुरू करें',
    'quickInquiry.disclaimer': 'कोई स्पैम नहीं। हम केवल आपकी पूछताछ के संबंध में संपर्क करेंगे।',
    'quickInquiry.successTitle': 'संपर्क करने के लिए धन्यवाद!',
    'quickInquiry.successMessage': 'हमारी टीम जल्द ही आपसे संपर्क करेगी।',
    'quickInquiry.errorMessage': 'कुछ गलत हो गया। कृपया पुनः प्रयास करें।',

    // For Retailers Page
    'forRetailers.hero.badge': '285+ दुकानदारों का भरोसा | 4.8/5 रेटिंग',
    'forRetailers.hero.title': 'अपनी दुकान को बनाइए',
    'forRetailers.hero.titleMiddle': 'एक',
    'forRetailers.hero.titleHighlight': 'आधुनिक बिज़नेस',
    'forRetailers.hero.description': 'ल्यूम आपको वो सभी स्मार्ट टूल देता है जिनसे आप क्विक कॉमर्स से टक्कर दे सकें — डिजिटल बिलिंग, ग्राहक की जानकारी और आसान सिस्टम जो किसी भी मोबाइल पर चलता है।',
    'forRetailers.hero.bookDemo': 'डेमो बुक करें',
    'forRetailers.hero.viewPricing': 'प्लान और कीमत देखें',
    
    'forRetailers.problems.title': 'आपकी रोज़ की परेशानियाँ — अब हल के साथ',
    'forRetailers.problems.subtitle': 'ल्यूम खास तौर पर भारतीय दुकानदारों की असली समस्याओं को ध्यान में रखकर बनाया गया है।',
    'forRetailers.problems.problem1': 'हाथ से बिल बनाने में रोज़ घंटों बर्बाद होते हैं',
    'forRetailers.problems.solution1': '10 सेकंड में डिजिटल बिल तैयार',
    'forRetailers.problems.problem2': 'ग्राहकों की कोई जानकारी नहीं, दोबारा ग्राहक नहीं आते',
    'forRetailers.problems.solution2': 'ग्राहक की पूरी जानकारी अपने आप सेव होती है',
    'forRetailers.problems.problem3': 'उधार सही से न संभाल पाने से नुकसान होता है',
    'forRetailers.problems.solution3': 'उधार की स्मार्ट ट्रैकिंग और ऑटो रिमाइंडर',
    'forRetailers.problems.problem4': 'असली मुनाफ़ा समझ में नहीं आता',
    'forRetailers.problems.solution4': 'रीयल-टाइम बिज़नेस रिपोर्ट और डैशबोर्ड',
    'forRetailers.problems.problem5': 'ग्राहक आपकी दुकान को भूल जाते हैं',
    'forRetailers.problems.solution5': 'व्हाट्सऐप पर ऑटो ऑफ़र और मैसेज',
    
    'forRetailers.howItWorks.title': '3 आसान स्टेप में डिजिटल बनिए',
    'forRetailers.howItWorks.step1.title': 'डाउनलोड करें और सेटअप करें',
    'forRetailers.howItWorks.step1.description': 'Play Store से ऐप डाउनलोड करें और कुछ ही मिनटों में अपनी दुकान की जानकारी जोड़ें।',
    'forRetailers.howItWorks.step1.time': 'सिर्फ 5 मिनट',
    'forRetailers.howItWorks.step2.title': 'बिल बनाना शुरू करें',
    'forRetailers.howItWorks.step2.description': 'GST के साथ प्रोफेशनल बिल बनाएं। ग्राहक की जानकारी अपने आप सेव होगी।',
    'forRetailers.howItWorks.step2.time': 'हर बिल 10 सेकंड में',
    'forRetailers.howItWorks.step3.title': 'बिक्री बढ़ाइए',
    'forRetailers.howItWorks.step3.description': 'रिपोर्ट और कस्टमर टूल्स का इस्तेमाल करके ग्राहकों को दोबारा लाएं।',
    'forRetailers.howItWorks.step3.time': 'औसतन 25% बढ़ोतरी',
    
    'forRetailers.industries.title': 'हर तरह की दुकान के लिए बनाया गया',
    'forRetailers.industries.subtitle': 'चाहे आप किराना, फैशन या इलेक्ट्रॉनिक्स बेचते हों — ल्यूम आपके बिज़नेस के अनुसार खुद को ढाल लेता है।',
    'forRetailers.industries.grocery.name': 'किराना और ग्रोसरी स्टोर',
    'forRetailers.industries.grocery.description': 'स्टॉक ट्रैकिंग, एक्सपायरी अलर्ट, सप्लायर मैनेजमेंट',
    'forRetailers.industries.fashion.name': 'फैशन और कपड़ों की दुकान',
    'forRetailers.industries.fashion.description': 'साइज़ और कलर मैनेजमेंट, सीज़नल सेल, लॉयल्टी सिस्टम',
    'forRetailers.industries.electronics.name': 'इलेक्ट्रॉनिक्स स्टोर',
    'forRetailers.industries.electronics.description': 'वारंटी ट्रैकिंग, सर्विस रिमाइंडर, बड़े बिल आसान',
    'forRetailers.industries.general.name': 'जनरल स्टोर',
    'forRetailers.industries.general.description': 'मल्टी कैटेगरी स्टॉक, फास्ट बिलिंग, उधार मैनेजमेंट',
    
    'forRetailers.testimonials.title': 'असली दुकानदारों के असली नतीजे',
    'forRetailers.testimonials.story1.metric': '40%',
    'forRetailers.testimonials.story1.outcome': 'ज़्यादा दोबारा आने वाले ग्राहक',
    'forRetailers.testimonials.story1.quote': 'अब मेरे ग्राहकों को व्हाट्सऐप पर बिल मिलता है। उन्हें पसंद आता है और वे दोबारा आते हैं।',
    'forRetailers.testimonials.story1.name': 'Vijay Grocery',
    'forRetailers.testimonials.story2.metric': '₹50K',
    'forRetailers.testimonials.story2.outcome': 'हर महीने ₹50,000 तक उधार की बचत',
    'forRetailers.testimonials.story2.quote': 'क्रेडिट ट्रैकिंग फ़ीचर ने उधार संभालने का तरीका ही बदल दिया है।',
    'forRetailers.testimonials.story2.name': 'Style Corner',
    'forRetailers.testimonials.story3.metric': '2 घंटे',
    'forRetailers.testimonials.story3.outcome': 'रोज़ 2 घंटे की बचत',
    'forRetailers.testimonials.story3.quote': 'जो काम घंटों में होता था अब मिनटों में हो जाता है। अब मैं ग्राहकों पर ध्यान दे सकता हूँ।',
    'forRetailers.testimonials.story3.name': 'City Mart',
    
    'forRetailers.roi.title': 'पहले ही महीने में ल्यूम अपनी कीमत निकाल देता है',
    'forRetailers.roi.description': 'हमारे दुकानदार शुरुआत के कुछ हफ्तों में ही नतीजे देखने लगते हैं। यहाँ वो है जो आप उम्मीद कर सकते हैं:',
    'forRetailers.roi.timeSaved.value': '2 घंटे/दिन',
    'forRetailers.roi.timeSaved.label': 'बिलिंग में रोज़ समय की बचत',
    'forRetailers.roi.creditRecovered.value': '₹15,000/महीना',
    'forRetailers.roi.creditRecovered.label': 'उधार की रकम वापस',
    'forRetailers.roi.repeatCustomers.value': '30% वृद्धि',
    'forRetailers.roi.repeatCustomers.label': 'ज़्यादा लौटने वाले ग्राहक',
    'forRetailers.roi.averageROI.value': '10 गुना निवेश पर रिटर्न',
    'forRetailers.roi.averageROI.label': 'औसतन 10 गुना रिटर्न',
    
    'forRetailers.testimonials.story1.location': 'अहमदाबाद',
    'forRetailers.testimonials.story2.location': 'मुंबई',
    'forRetailers.testimonials.story3.location': 'ठाणे',
    
    'forRetailers.cta.title': 'शुरू करने के लिए तैयार हैं?',
    'forRetailers.cta.feature1': 'सभी फीचर्स के साथ लाइव डेमो',
    'forRetailers.cta.feature2': 'कोई कार्ड की ज़रूरत नहीं',
    'forRetailers.cta.feature3': 'फ्री सेटअप और सपोर्ट',
    'forRetailers.cta.feature4': 'हर एंड्रॉयड मोबाइल पर काम करता है',
    'forRetailers.cta.feature5': 'जब चाहें बंद करें',
    'forRetailers.cta.bookDemo': 'डेमो बुक करें',
    'forRetailers.cta.viewPricing': 'या प्लान देखें',
    
    // Footer
    'footer.tagline': 'हम बिलिंग को दुकानदारों के लिए ग्रोथ इंजन में बदलते हैं।',
    'footer.company': 'कंपनी',
    'footer.products': 'उत्पाद',
    'footer.solutions': 'समाधान',
    'footer.resources': 'संसाधन',
    'footer.about': 'हमारे बारे में',
    'footer.careers': 'करियर',
    'footer.investors': 'निवेशक',
    'footer.contact': 'संपर्क करें',
    'footer.webPos': 'ऑनलाइन बिलिंग सिस्टम',
    'footer.posPlugin': 'बिलिंग सिस्टम का अतिरिक्त फीचर',
    'footer.analytics': 'एनालिटिक्स डैशबोर्ड',
    'footer.campaign': 'कैंपेन मैनेजर',
    'footer.lume': 'ल्यूम',
    'footer.mpos': 'MPos – मोबाइल POS',
    'footer.lumeShopComingSoon': 'ल्यूम शॉप (जल्द आ रहा है)',
    'footer.smartBilling': 'स्मार्ट बिलिंग',
    'footer.digitalBills': 'व्हाट्सऐप पर डिजिटल बिल',
    'footer.customerAnalytics': 'ग्राहक एनालिटिक्स',
    'footer.loyalty': 'लॉयल्टी और कूपन',
    'footer.campaignManagement': 'कैंपेन प्रबंधन',
    'footer.pricing': 'प्राइसिंग',
    'footer.caseStudies': 'केस स्टडीज',
    'footer.blog': 'ब्लॉग',
    'footer.guides': 'गाइड',
    'footer.helpCenter': 'हेल्प सेंटर',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'नियम और शर्तें',
    'footer.copyright': 'सभी अधिकार सुरक्षित।',
    
    // Header Navigation
    'nav.forRetailers': 'दुकानदारों के लिए',
    'nav.solutions': 'समाधान',
    'nav.industries': 'श्रेणी',
    'nav.features': 'फ़ीचर्स',
    'nav.products': 'प्रोडक्ट्स',
    'nav.resources': 'जानकारी',
    'nav.pricing': 'कीमतें',
    'nav.financials': 'फाइनेंशियल्स',
    'nav.bookDemo': 'डेमो बुक करें',

    // Financials Page
    'financials.title': 'फाइनेंशियल्स',

    // Products Page
    'products.hero.titleLine1': 'ऐसी बिलिंग, जो आपके',
    'products.hero.titleLine1Part2Before': 'बिज़नेस को',
    'products.hero.titleLine1Part2After': 'सच में समझे',
    'products.hero.titleLine2': 'ल्यूम आपकी बिलिंग, ग्राहक जानकारी, कैम्पेन और एनालिटिक्स को',
    'products.hero.titleLine3': 'एक ही स्मार्ट रिटेल प्लेटफ़ॉर्म में जोड़ता है —',
    'products.hero.titleLine4': 'ताकि आपकी दुकान बेहतर चले, ग्राहक जुड़े रहें और बिक्री बढ़े।',
    'products.hero.bookDemo': 'डेमो बुक करें',
    'products.hero.seeFeatures': 'सभी फ़ीचर्स देखें',
    'products.whatIsLume.title': 'ल्यूम क्या है?',
    'products.whatIsLume.point1': 'ल्यूम एक पूरा रिटेल प्लेटफ़ॉर्म है, जो आपको सिर्फ बिल बनाने से आगे ले जाता है।',
    'products.whatIsLume.point2': 'यह आपके मौजूदा POS या वेब बिलिंग सिस्टम के साथ काम करता है, हर बिल को अपने-आप पढ़ता है और उस बिलिंग डेटा को ग्राहक समझ, लॉयल्टी और बिज़नेस ग्रोथ में बदल देता है।',
    'products.coreCapabilities.title': 'ल्यूम से आप क्या कर सकते हैं',
    'products.coreCapabilities.billing.title': 'बिलिंग और POS इंटीग्रेशन',
    'products.coreCapabilities.billing.desc': 'बिलिंग जो तेज़ भी है और लचीली भी',
    'products.coreCapabilities.billing.feature1': 'टैक्स और नॉन-टैक्स बिलिंग',
    'products.coreCapabilities.billing.feature2': 'क्विक बिलिंग और इमेज बिलिंग',
    'products.coreCapabilities.billing.feature3': 'अलग-अलग बिल टेम्पलेट',
    'products.coreCapabilities.billing.feature4': 'POS प्लग-इन (किसी भी मौजूदा POS से कनेक्ट करें)',
    'products.coreCapabilities.digitalBills.title': 'स्मार्ट डिजिटल बिल',
    'products.coreCapabilities.digitalBills.desc': 'हर बिल को ग्राहक से जुड़ने का ज़रिया बनाइए',
    'products.coreCapabilities.digitalBills.feature1': 'व्हाट्सऐप / SMS / ईमेल से बिल भेजें',
    'products.coreCapabilities.digitalBills.feature2': 'बिल के अंदर ऑफ़र और प्रमोशन',
    'products.coreCapabilities.digitalBills.feature3': 'फ़ीडबैक और गूगल रेटिंग लिंक',
    'products.coreCapabilities.digitalBills.feature4': 'सोशल शेयरिंग और रेफ़र एंड अर्न प्रोग्राम',
    'products.coreCapabilities.loyalty.title': 'ग्राहक और लॉयल्टी सिस्टम',
    'products.coreCapabilities.loyalty.desc': 'हर खरीद के साथ रिश्ते मज़बूत करें',
    'products.coreCapabilities.loyalty.feature1': 'ग्राहक अपने-आप जुड़ जाते हैं',
    'products.coreCapabilities.loyalty.feature2': 'पूरी खरीदारी हिस्ट्री',
    'products.coreCapabilities.loyalty.feature3': 'लॉयल्टी पॉइंट्स और कूपन',
    'products.coreCapabilities.loyalty.feature4': 'दोबारा आने वाले ग्राहकों की ट्रैकिंग',
    'products.coreCapabilities.analytics.title': 'एनालिटिक्स और रिपोर्ट्स',
    'products.coreCapabilities.analytics.desc': 'अब फैसले अनुमान से नहीं, डेटा से होंगे',
    'products.coreCapabilities.analytics.feature1': 'बिक्री और प्रोडक्ट एनालिटिक्स',
    'products.coreCapabilities.analytics.feature2': 'ग्राहक व्यवहार की जानकारी',
    'products.coreCapabilities.analytics.feature3': 'समय के हिसाब से इनसाइट्स',
    'products.coreCapabilities.analytics.feature4': 'डाउनलोड करने योग्य रिपोर्ट्स',
    'products.coreCapabilities.campaign.title': 'कैम्पेन मैनेजर',
    'products.coreCapabilities.campaign.desc': 'सही ग्राहक को, सही समय पर पहुँचिए',
    'products.coreCapabilities.campaign.feature1': 'ग्राहक सेगमेंट के हिसाब से कैम्पेन',
    'products.coreCapabilities.campaign.feature2': 'व्हाट्सऐप, SMS जैसे कई चैनल',
    'products.coreCapabilities.campaign.feature3': 'कैम्पेन परफॉर्मेंस ट्रैकिंग',
    'products.coreCapabilities.campaign.feature4': 'ऑटोमेटेड वर्कफ़्लो',
    'products.howItWorks.title': 'ल्यूम आपके बिज़नेस में कैसे फिट होता है',
    'products.howItWorks.step1.title': 'POS / वेब / प्लग-इन से बिल बनाएँ',
    'products.howItWorks.step1.desc': 'अपना मौजूदा सिस्टम इस्तेमाल करें या ल्यूम का वेब POS।',
    'products.howItWorks.step2.title': 'ल्यूम हर बिल का डेटा जोड़ता है',
    'products.howItWorks.step2.desc': 'हर ट्रांज़ैक्शन अपने-आप सेव और प्रोसेस होती है।',
    'products.howItWorks.step3.title': 'ग्राहक को स्मार्ट डिजिटल बिल मिलता है',
    'products.howItWorks.step3.desc': 'जिसमें ऑफ़र, फ़ीडबैक और ज़रूरी लिंक होते हैं।',
    'products.howItWorks.step4.title': 'डेटा से एनालिटिक्स, लॉयल्टी और कैम्पेन चलते हैं',
    'products.howItWorks.step4.desc': 'जिससे बेहतर फैसले और ज़्यादा ग्राहक जुड़ाव होता है।',
    'products.whoIsLumeFor.title': 'आपके साथ-साथ बढ़ने के लिए बना',
    'products.whoIsLumeFor.singleStore.title': 'सिंगल स्टोर रिटेलर',
    'products.whoIsLumeFor.singleStore.desc': 'जो अपनी दुकान को डिजिटल बनाना चाहते हैं',
    'products.whoIsLumeFor.multiStore.title': 'मल्टी-स्टोर बिज़नेस',
    'products.whoIsLumeFor.multiStore.desc': 'एक ही डैशबोर्ड से कई दुकानों का मैनेजमेंट',
    'products.whoIsLumeFor.growingChains.title': 'बढ़ती हुई रिटेल चेन',
    'products.whoIsLumeFor.growingChains.desc': 'एंटरप्राइज़-लेवल टूल्स के साथ स्केल करें',
    'products.lumeShop.title': 'ल्यूम शॉप के साथ ल्यूम को और आगे बढ़ाइए',
    'products.lumeShop.desc': 'ल्यूम शॉप आपकी दुकान को एक हाइपरलोकल ऑनलाइन स्टोर में बदल देता है। ऑर्डर, ग्राहक और डेटा — सब कुछ ल्यूम से जुड़ा रहता है।',
    'products.lumeShop.comingSoon': 'जल्द आ रहा है',
    'products.lumeShop.preview': 'ल्यूम शॉप प्रीव्यू',
    'products.trust.retailers': 'रिटेलर्स',
    'products.trust.transactions': 'ट्रांज़ैक्शन्स',
    'products.trust.rating': 'रेटिंग',
    'products.trust.growth': 'औसतन बिक्री में बढ़ोतरी',
    'products.trust.testimonial': 'ल्यूम ने हमारी दुकान संभालने का तरीका ही बदल दिया। अब सब कुछ एक-दूसरे से जुड़ा है।',
    'products.trust.testimonialAuthor': 'रिटेल स्टोर ओनर',
    'products.cta.title': 'ल्यूम को लाइव देखकर समझिए',
    'products.cta.bookDemo': 'डेमो बुक करें',
    'products.cta.viewPricing': 'प्राइसिंग देखें',

    // Products page FAQ (Hindi)
    'products.faq.title': 'अक्सर पूछे जाने वाले सवाल',
    'products.faq.q1': 'ल्यूम क्या है?',
    'products.faq.a1': 'ल्यूम भारतीय रिटेलर्स के लिए डिजिटल बिलिंग, कस्टमर एंगेजमेंट और मार्केटिंग प्लेटफ़ॉर्म है। यह हर बिल को व्हाट्सऐप पर डिजिटल रसीद में बदल देता है, ग्राहक की जानकारी अपने आप कैप्चर करता है, और लॉयल्टी व मार्केटिंग कैंपेन चलाने में मदद करता है ताकि ग्राहक वापस आएं।',
    'products.faq.q2': 'डिजिटल बिल क्या है और यह कागज़ की रसीद से कैसे अलग है?',
    'products.faq.a2': 'डिजिटल बिल आपके इनवॉइस का पेपरलेस रूप है, जो प्रिंट रसीद की जगह तुरंत ग्राहक को व्हाट्सऐप, SMS या ईमेल पर भेजा जाता है। यह ग्राहक की जानकारी अपने आप कैप्चर करता है, जिससे हर बिक्री से आपकी कस्टमर लिस्ट भी बनती है।',
    'products.faq.q3': 'क्या मैं ल्यूम से मार्केटिंग कैंपेन चला सकता हूँ?',
    'products.faq.a3': 'हाँ। ल्यूम का कैंपेन मैनेजर आपको डिजिटल बिल से मिले ग्राहकों को ऑफ़र, छूट और त्योहारी शुभकामनाएं भेजने देता है, जिससे आप बिना किसी अलग टूल के टारगेटेड मार्केटिंग कैंपेन चला सकते हैं।',
    'products.faq.q4': 'ल्यूम ग्राहकों को वापस लाने में कैसे मदद करता है?',
    'products.faq.a4': 'ल्यूम डिजिटल बिल, लॉयल्टी कूपन और व्हाट्सऐप कैंपेन को जोड़ता है, जिससे एक बार खरीदने वाले ग्राहक भी ऑफ़र के लिए योग्य हो जाते हैं और समय के साथ बार-बार खरीदारी करने वाले ग्राहक बनते हैं।',
    'products.faq.q5': 'क्या ल्यूम इस्तेमाल करने के लिए मुझे अपना मौजूदा बिलिंग या POS सिस्टम बदलना होगा?',
    'products.faq.a5': 'नहीं। आप सीधे ल्यूम में बिलिंग कर सकते हैं, या अपना मौजूदा POS/बिलिंग सिस्टम कनेक्ट कर सकते हैं ताकि डिजिटल बिल, कस्टमर डेटा और एनालिटिक्स एक ही जगह मिलें — बिना यह बदले कि आप अभी कैसे बिल बनाते हैं।',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Get from localStorage or default to EN
    const saved = localStorage.getItem('language') as Language;
    return saved && (saved === 'EN' || saved === 'HI') ? saved : 'EN';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const val = translations[language][key];
    return (val !== undefined && val !== null) ? val : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

